namespace Harness.Checks.Maintainability;

/// <summary>Long-form content for `harness explain maintainability.csharp`.</summary>
internal static class MaintainabilityExplanation
{
    public const string Text =
        """
        Rationale
          Size is a cheap observable signal that a piece of C# is becoming expensive to
          change. It is a signal, not a verdict: the gate measures it and names it precisely.
          Findings originate as advisory evidence,
          while the default required repository policy makes every unresolved finding
          blocking. A repository paying down known findings can opt into advisory policy.

        Discovery
          Every Git-tracked `.cs` file is analyzed. Generated, vendored and build-output
          locations are excluded, as are files named `*.g.cs`, `*.generated.cs` and
          `*.Designer.cs`, and files whose first five lines carry the `<auto-generated>`
          marker. Exclusion is by name and by declared marker only, so a reader can predict
          it. A repository with no remaining C# source is not applicable, never a pass.

        Formulas
          Each file is first reduced to code: comment text, string and character literal
          content, and preprocessor directives are replaced with spaces, keeping every
          offset and line number intact. Every count below reads that reduced text.

          file logical lines          physical lines that carry code, or continue a
                                      multi-line string literal
          type logical lines          the same count between a type declaration and its
                                      closing brace, nested types included
          method logical lines        the same count between a method or constructor
                                      declaration and its closing brace, from the first
                                      line of the signature
        Names
          The names above are the whole claim. Logical lines measure source size, not the
          number of statements, execution paths or responsibilities.

          Repository pins through 1.5 additionally reproduce the legacy `constructor
          parameter count` and `public declared members` measurements and their comparison
          points. They were removed in 1.6 because data values, options, facades and services
          have legitimately different width, so repository-wide counts had no universal
          remediation. In particular, treating a positional record as data but a data class
          as collaborators made the constructor rule depend on syntax rather than intent.

        Limits
          Multi-line literals contribute lines because their size remains authored source,
          while comments and blank lines do not. Lambdas and local functions are counted
          against the member that contains them, and nested types against the type that
          contains them. Conditional compilation is not evaluated: directives are removed
          and every branch of the source is read. Constructs the reader does not recognize
          are treated as ordinary blocks, which costs a measurement rather than producing a
          wrong one.

        Possible damage
          A measurement can be wrong. An unfamiliar declaration form can be attributed to
          the wrong subject or line, and a value can be inflated by code the metric counts
          against the wrong member. Check the reported location before acting: a refactor
          driven by a misread measurement changes working code for no reason, and it does
          so with the confidence of a number. A finding that does not survive that check
          should be tuned or suppressed with a reason instead of driving a harmful refactor.

        Comparison points
          The number a measurement is reported against is a configurable comparison point.
          Exceeding it is a fact the required policy enforces, not proof of a semantic defect:
          a deliberate, well-named 300-line state machine may instead need a named exception
          or a better repository setting. Every comparison point is configured under
          `settings.maintainability.csharp` in `.harness.json`.

        Remediation
          Read the subject at the reported location and decide. A refactor has its own
          cost: splitting a cohesive type to satisfy a line count adds indirection and
          spreads one decision across several files. Act when the measurement matches
          something you already find hard to change. Engineering judgement decides here;
          the harness supplies the evidence and will not edit the code.
        """;
}
