namespace Harness.Checks.Maintainability;

/// <summary>Long-form content for `harness explain maintainability.csharp`.</summary>
internal static class MaintainabilityExplanation
{
    public const string Text =
        """
        Rationale
          Size, branching and surface area are the cheapest observable signals that a piece
          of C# is becoming expensive to change. They are signals, not verdicts: the gate
          measures them, names them precisely and stops there. Every finding is advisory
          and never produces exit code 1, because an approximate measurement must not
          impose one architectural taste on every repository.

        Discovery
          Every Git-tracked `.cs` file is analyzed. Generated, vendored and build-output
          locations are excluded, as are files named `*.g.cs`, `*.generated.cs` and
          `*.Designer.cs`, and files whose first five lines carry the `<auto-generated>`
          marker. Exclusion is by name and by declared marker only, so a reader can predict
          it. A repository with no remaining C# source is not applicable, never a pass.

        Formulas
          Each file is first reduced to code: comment text, string and character literal
          content, and preprocessor directives are replaced with spaces, keeping every
          offset and line number intact. Every count below reads that reduced text.

          file logical lines          physical lines that carry code, or continue a
                                      multi-line string literal
          type logical lines          the same count between a type declaration and its
                                      closing brace, nested types included
          method logical lines        the same count between a method or constructor
                                      declaration and its closing brace, from the first
                                      line of the signature
          lexical branch count        1 plus the occurrences of `if`, `for`, `foreach`,
                                      `while`, `do`, `case`, `catch`, `when`, `&&`, `||`
                                      and `??` inside the member
          constructor parameter count parameters of a declared constructor, or of a
                                      primary constructor on a class or record
          public declared members     declarations beginning with `public` directly inside
                                      one type body
          using directive fan-out     `using` directives outside any type in one file

        Names
          The names above are the whole claim. `using directive fan-out` counts import
          directives and is not semantic coupling: it says nothing about which types are
          used, how often, or in which direction. `constructor parameter count` counts
          parameters and is not a dependency count: a parameter may be a value, an option
          or an already-grouped context. `lexical branch count` counts tokens; it is
          not a compiler control-flow graph, and has no notion of reachability, of paths
          that cannot be taken, or of exception edges. `public declared members` counts
          declarations, not the size of the reachable API.

        Limits
          The reader is lexical. Interpolation holes are masked with the literal that
          contains them, so branching written inside one is not counted. Ternary
          conditionals, pattern combinators and switch-expression arms are not counted.
          Lambdas and local functions are counted against the member that contains them,
          and nested types against the type that contains them. Conditional compilation is
          not evaluated: directives are removed and every branch of the source is read.
          Constructs the reader does not recognize are treated as ordinary blocks, which
          costs a measurement rather than producing a wrong one.

        Possible damage
          A measurement can be wrong. An unfamiliar declaration form can be attributed to
          the wrong subject or line, and a value can be inflated by code the metric counts
          against the wrong member. Check the reported location before acting: a refactor
          driven by a misread measurement changes working code for no reason, and it does
          so with the confidence of a number. Nothing here is blocking, so a finding that
          does not survive that check costs only the reading.

        Comparison points
          The number a measurement is reported against is a comparison point, not a
          threshold and not a budget. It exists so a value has a scale; exceeding it is an
          invitation to look, and a deliberate, well-named 300-line state machine that
          exceeds it is not a defect.

        Remediation
          Read the subject at the reported location and decide. A refactor has its own
          cost: splitting a cohesive type to satisfy a line count adds indirection and
          spreads one decision across several files, and reducing a constructor's
          parameters by introducing a container can hide a real dependency rather than
          remove it. Act when the measurement matches something you already find hard to
          change. Engineering judgement decides here; the harness supplies the evidence and
          will not edit the code.
        """;
}
