using Harness.Git;

namespace Harness.Checks.CSharp;

internal static class CSharpSources
{
    public const string NothingToAnalyze =
        "no tracked C# source outside generated and build-output locations";

    private static readonly string[] GeneratedSuffixes = [".g.cs", ".generated.cs", ".designer.cs"];

    public static (IReadOnlyList<CSharpSource> Sources, string? Failure) Discover(GitRepository repository)
    {
        var candidates = repository.TrackedEntries
            .Where(entry => entry.Path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
            .Where(entry => !RepositoryLocations.IsGenerated(entry.Path))
            .Where(entry => !GeneratedSuffixes.Any(suffix =>
                entry.Path.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)))
            .OrderBy(entry => entry.Path, StringComparer.Ordinal);

        var sources = new List<CSharpSource>();
        foreach (var entry in candidates)
        {
            var (text, failure) = repository.ReadTrackedText(entry);
            if (text is null)
            {
                return ([], failure ?? $"Could not read '{entry.Path}'.");
            }

            if (!IsGeneratedContent(text))
            {
                sources.Add(CSharpSource.Read(entry.Path, text));
            }
        }

        return (sources, null);
    }

    // Generated markers are conventionally emitted at the start of a file.
    private static bool IsGeneratedContent(string text)
        => text.Split('\n').Take(5).Any(line => line.Contains("<auto-generated", StringComparison.Ordinal));
}
