using Harness.Git;

namespace Harness.Checks.CSharp;

/// <summary>
/// Which tracked C# the harness is willing to analyze. Both heuristic gates read the same
/// answer, so a file excluded from one measurement cannot reappear in another, and neither
/// gate has its own private idea of what generated code is.
/// </summary>
internal static class CSharpSources
{
    /// <summary>What is reported when discovery found nothing to analyze.</summary>
    public const string NothingToAnalyze =
        "no tracked C# source outside generated and build-output locations";

    /// <summary>File names the .NET ecosystem reserves for tool output rather than authored code.</summary>
    private static readonly string[] GeneratedSuffixes = [".g.cs", ".generated.cs", ".designer.cs"];

    /// <summary>
    /// Every analyzable source, in path order. A source the harness could not read is not
    /// evidence of anything, so it ends discovery with a reason instead of a shorter list.
    /// </summary>
    public static (IReadOnlyList<CSharpSource> Sources, string? Failure) Discover(GitRepository repository)
    {
        var candidates = repository.TrackedEntries
            .Where(entry => entry.Path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
            .Where(entry => !RepositoryLocations.IsGenerated(entry.Path))
            .Where(entry => !GeneratedSuffixes.Any(suffix =>
                entry.Path.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)))
            .OrderBy(entry => entry.Path, StringComparer.Ordinal);

        var sources = new List<CSharpSource>();
        foreach (var entry in candidates)
        {
            var (text, failure) = repository.ReadTrackedText(entry);
            if (text is null)
            {
                return ([], failure ?? $"Could not read '{entry.Path}'.");
            }

            if (!IsGeneratedContent(text))
            {
                sources.Add(CSharpSource.Read(entry.Path, text));
            }
        }

        return (sources, null);
    }

    /// <summary>
    /// The marker generators agree on. Reading it from the first lines keeps the exclusion
    /// explainable: a file is excluded because it says it is generated, not because the
    /// harness guessed from its shape.
    /// </summary>
    private static bool IsGeneratedContent(string text)
        => text.Split('\n').Take(5).Any(line => line.Contains("<auto-generated", StringComparison.Ordinal));
}
