namespace Harness.Checks.Duplication;

/// <summary>Long-form content for `harness explain duplication.csharp`.</summary>
internal static class DuplicationExplanation
{
    public const string Text =
        """
        Rationale
          The same structure written out in several files is the cheapest observable sign
          that an abstraction is missing, or that one was copied instead of called. The
          gate finds where that happened and stops there. Findings originate as advisory
          evidence because a lexical match is a reason to read two places, not proof that
          they mean the same thing. An explicit required repository policy nevertheless
          blocks every unresolved match; advisory is an explicit migration state.

        Discovery
          Every Git-tracked `.cs` file is analyzed. Generated, vendored and build-output
          locations are excluded, as are files named `*.g.cs`, `*.generated.cs` and
          `*.Designer.cs`, and files whose first five lines carry the `<auto-generated>`
          marker. Exclusion is by name and by declared marker only, so a reader can predict
          it, and no repository-local analyzer script or exclusion list is involved. A
          repository with no remaining C# source is not applicable, never a pass.

        Normalization
          Each file is first reduced to code: comment text, string and character literal
          content, and preprocessor directives are replaced with spaces. What remains is
          turned into one token sequence per physical line, by these rules and no others:

          comment, directive        contributes nothing
          string literal            one `"` token, whatever it contains
          character literal         one `'` token, whatever it contains
          numeric literal           one `#` token
          C# keyword                itself, so `if` and `while` never match each other
          any other word            `n`, so every identifier reads the same
          any other character       itself
          whitespace                separates tokens and never survives; a line with no
                                    tokens leaves no trace, so blank lines and reflowed
                                    formatting do not affect a match

        Unit of comparison
          The unit is a configurable window of consecutive normalized lines carrying a
          configurable minimum number of tokens in total. The initialized profile uses 30 lines and 90
          tokens. Two windows repeat when their token sequences are identical. Windows
          below the token count are not compared at all: lines of braces, `return`s and
          closing parentheses are identical in every file and are not something anyone can
          extract.

          A repetition is reported once, not once per window. When a group of matching
          windows is found it is grown line by line, backwards and forwards, for as long
          as every occurrence still agrees. What the report names is the whole repeated
          region, as a physical line span, in every file it occurs in.

          Growth stops at lines a repetition has already claimed, so no line is ever
          reported twice. Three copies of which two run longer than the third therefore
          read as two findings that do not overlap — what all three share, and then what
          the remaining two share — rather than as one finding quietly containing another.

          Only repetitions that span at least two files are reported. Repetition inside one
          file is left to the reader who already has the whole file open.

        Names
          The name is the whole claim. `lexically repeated block` means the two regions
          produce the same tokens after the normalization above. That is
          not proven duplicate behaviour: the gate has no types, no bindings, no overload
          resolution and no notion of what any of the identifiers it erased referred to.

        Limits
          The reader is lexical. An interpolation hole is masked with the literal that
          contains it, so code written inside one is not compared. Structurally identical
          code that differs by one token — an added argument, a different operator — does
          not match, and a repetition shorter than the configured window is not reported at
          all. Conditional compilation is not evaluated: directives are removed and every
          branch of the source is read.

        False positives
          Normalization erases exactly what makes some similar-looking code different.
          Property and field declarations, `switch` arms, builder chains, DTO shapes, test
          arrange blocks and generated-looking boilerplate all converge on the same tokens
          while referring to unrelated things; a run of them will be reported and is often
          nothing. Two implementations of the same interface that legitimately share a
          shape are reported for the same reason.

        Possible damage
          Extracting a shared helper from two blocks that only look alike couples two
          things that had no reason to change together, and every later change to one of
          them then arrives as a parameter or a flag on the shared helper. That is worse
          than the repetition it removed. A match that does not survive reading should be
          handled by tuning the detector or by advisory policy instead of forcing the wrong
          abstraction.

        Remediation
          Open both locations before deciding anything. Extract when the two blocks encode
          one rule that must stay the same — when a change to one would be a bug if it did
          not reach the other. Leave them alone when they merely look alike, when they
          belong to different layers or bounded contexts, when they are tests whose
          explicitness is the point, or when the shared abstraction would need a parameter
          for every difference. Engineering judgement decides here; the harness supplies
          the evidence and will not edit the code. Tune `settings.duplication.csharp.windowLines`
          and `minimumTokens` when the repository's ordinary explicit patterns make the
          initialized settings noisy; use advisory policy temporarily while known matches are paid down,
          or `off` only when the whole measurement is unwanted.
        """;
}
