namespace Harness.Checks.Comments;

internal static class CommentLineExplanation
{
    public const string Text =
        """
        Rationale
          Comments are useful when they preserve information the code cannot express. They
          become a parallel narrative when they restate names and control flow, and that
          narrative can drift while the compiler keeps accepting the code. A density limit
          makes comment-heavy files blocking and asks for deliberate review; it does not
          claim that every comment below the limit is useful.

        Rule
          A file violates the rule when it reaches the configured `minimumCommentLines` and
          comments exceed the configured `percentageLimit` of authored physical lines. An authored
          line is a non-empty line carrying code, a string continuation or a comment. A line
          carrying both code and a comment appears once in the denominator and once in the
          comment numerator.

          A physical line is counted once when any part of a `//`, `///` or `/* ... */`
          comment occurs on it. Inline comments and XML documentation count. Comment-shaped
          text inside string and character literals does not count.

        When a comment is warranted
          Keep a comment only when the code alone cannot make one of these clear:
          - the reason for a non-obvious decision or constraint;
          - an important invariant;
          - a workaround, with its source or removal condition;
          - a public API contract when the language or repository convention requires it.

          Express everything else in names and structure: a retelling of the code, a doc
          comment that repeats a function or key name, narration, decorative separators,
          commented-out code, and a TODO without a concrete issue are not durable context.

        Evidence
          The check reads Git-tracked `.cs` files through the shared lexical C# reader.
          Generated, vendored and build-output locations, generated file-name suffixes and
          files carrying an `<auto-generated>` marker are excluded. Unreadable evidence
          makes the check incomplete rather than shortening the count silently.

        Limits
          This is a lexical count, not a judgement of whether prose is true or valuable.
          Comments inside interpolation holes are covered by the containing string region
          and are not counted; a preprocessor directive line is masked as one directive,
          including any trailing comment. Both values live under
          `settings.comments.csharp` in `.harness.json`; they are repository policy, not
          industry constants. A file
          with an unusually dense set of indispensable comments can use
          `policy.comments.csharp`.

        Remediation
          Review the reported file. Delete stale, obvious and decorative prose; remove
          commented-out code; and link each TODO to a concrete task. If names and structure
          can carry the meaning, refactor names and structure instead of adding a comment.
          Keep concise comments that preserve non-obvious reasons, invariants, sourced
          workarounds or required API contracts.
        """;
}
