namespace Harness.Tests;

public sealed class CommentLineTests
{
    private const string Check = "comments.csharp";

    [Fact]
    public void A_repository_without_csharp_sources_is_not_applicable()
    {
        using var repository = Fixtures.Compliant();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Check);

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("not applicable"), run.Output);
    }

    [Fact]
    public void A_file_at_the_percentage_limit_passes()
    {
        using var repository = SourceRepository(Source(commentLines: 10, codeLines: 30));

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Check);

        Assert.Equal(0, run.ExitCode);
    }

    [Fact]
    public void A_file_above_the_percentage_limit_is_a_blocking_violation_with_remediation()
    {
        using var repository = SourceRepository(Source(commentLines: 10, codeLines: 29));

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Check);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("10 of 39 authored physical lines"), run.Output);
        Assert.True(run.OutputContains("25.6%"), run.Output);
        Assert.True(run.OutputContains("25% limit"), run.Output);
        Assert.True(run.OutputContains("minimum of 10"), run.Output);
        Assert.True(run.OutputContains("non-obvious reason"), run.Output);
        Assert.True(run.OutputContains("names and structure"), run.Output);
    }

    [Fact]
    public void A_dense_small_file_below_the_comment_floor_passes()
    {
        using var repository = SourceRepository(Source(commentLines: 9, codeLines: 1));

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Check);

        Assert.Equal(0, run.ExitCode);
    }

    [Fact]
    public void Repository_settings_change_the_comment_policy()
    {
        using var repository = SourceRepository(
            Source(commentLines: 10, codeLines: 29),
            Frame.Answering().Settings(
                """{ "comments.csharp": { "percentageLimit": 30, "minimumCommentLines": 11 } }"""));

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Check);

        Assert.Equal(0, run.ExitCode);
    }

    [Fact]
    public void Each_physical_line_with_a_comment_is_counted_once()
    {
        var source = Source(commentLines: 0, codeLines: 30)
            + "    /* one\n"
            + new string('\n', 8)
            + "       ten */ public int Value => 1; // still ten\n";
        using var repository = SourceRepository(source);

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Check);

        Assert.Equal(0, run.ExitCode);
    }

    [Fact]
    public void Comment_shapes_inside_literals_do_not_count()
    {
        var source = string.Concat(
            Enumerable.Repeat("public string Value => \"// not a comment /* either */\";\n", 30));
        using var repository = SourceRepository(source);

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Check);

        Assert.Equal(0, run.ExitCode);
    }

    [Fact]
    public void Comments_on_preprocessor_directive_lines_are_out_of_scope()
    {
        var source = string.Concat(Enumerable.Repeat("#if DEBUG // reason\n#endif\n", 10))
            + "public class Quiet { }\n";
        using var repository = SourceRepository(source);

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Check);

        Assert.Equal(0, run.ExitCode);
    }

    [Fact]
    public void Xml_docs_and_inline_comments_count()
    {
        var source = string.Concat(Enumerable.Repeat("/// contract\n", 9))
            + "public int Value => 1; // reason\n"
            + CodeLines(29);
        using var repository = SourceRepository(source);

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Check);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("10 of 39 authored physical lines"), run.Output);
    }

    [Fact]
    public void Generated_and_untracked_sources_are_excluded()
    {
        using var repository = Fixtures.Compliant()
            .WriteFile("src/App/Loud.g.cs", Source(commentLines: 10, codeLines: 1))
            .WriteFile("src/App/obj/Loud.cs", Source(commentLines: 10, codeLines: 1))
            .WriteFile("src/App/Marked.cs", "// <auto-generated />\n" + Source(commentLines: 10, codeLines: 1))
            .Commit()
            .WriteFile("src/App/Untracked.cs", Source(commentLines: 10, codeLines: 1));

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Check);

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("not applicable"), run.Output);
    }

    [Fact]
    public void Explain_states_when_comments_are_warranted_and_what_to_remove()
    {
        using var repository = Fixtures.Compliant();

        var run = HarnessCli.Run(repository.Path, "explain", Check);

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("When a comment is warranted"), run.Output);
        Assert.True(run.OutputContains("important invariant"), run.Output);
        Assert.True(run.OutputContains("removal condition"), run.Output);
        Assert.True(run.OutputContains("commented-out code"), run.Output);
        Assert.True(run.OutputContains("TODO without a concrete issue"), run.Output);
        Assert.True(run.OutputContains("refactor names and structure"), run.Output);
        Assert.True(run.OutputContains("minimumCommentLines"), run.Output);
        Assert.True(run.OutputContains("percentageLimit"), run.Output);
    }

    private static RepositoryFixture SourceRepository(string source, Frame? frame = null)
        => Fixtures.Compliant(frame ?? Frame.AllPresent()).WriteFile("src/App/Source.cs", source).Commit();

    private static string Source(int commentLines, int codeLines)
        => string.Concat(Enumerable.Range(1, commentLines).Select(line => $"// reason {line}\n"))
            + CodeLines(codeLines);

    private static string CodeLines(int count)
        => string.Concat(Enumerable.Range(1, count).Select(line => $"public class Type{line} {{ }}\n"));
}
