namespace Harness.Tests;

/// <summary>The comment density rule read through the YAML and TypeScript readers.</summary>
public sealed class CommentLineLanguageTests
{
    private const string Yaml = "comments.yaml";

    private const string TypeScript = "comments.typescript";

    [Fact]
    public void A_repository_without_yaml_or_typescript_is_not_applicable_to_both()
    {
        using var repository = Fixtures.Compliant();

        var yaml = HarnessCli.RunVerbose(repository.Path, "check", "--only", Yaml);
        var typescript = HarnessCli.RunVerbose(repository.Path, "check", "--only", TypeScript);

        Assert.Equal(0, yaml.ExitCode);
        Assert.True(yaml.OutputContains("not applicable"), yaml.Output);
        Assert.Equal(0, typescript.ExitCode);
        Assert.True(typescript.OutputContains("not applicable"), typescript.Output);
    }

    [Fact]
    public void A_yaml_file_above_the_limit_is_a_blocking_violation()
    {
        var source = Lines(12, line => $"# reason {line}") + Lines(100, line => $"key{line}: value");
        using var repository = Fixtures.Compliant().WriteFile("deploy/values.yml", source).Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Yaml);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("deploy/values.yml"), run.Output);
        Assert.True(run.OutputContains("12 of 112 authored physical lines"), run.Output);
        Assert.True(run.OutputContains("8% limit"), run.Output);
    }

    [Fact]
    public void Hash_inside_quoted_and_block_scalars_is_yaml_content()
    {
        var source = Lines(10, line => $"quoted{line}: \"channel #{line}\" # trailing")
            + "script: |\n"
            + Lines(30, line => $"  # not a comment {line}")
            + "single: 'it''s #{tag}'\n"
            + Lines(100, line => $"key{line}: value");
        using var repository = Fixtures.Compliant().WriteFile("ci.yaml", source).Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Yaml);

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("comments.yaml"), run.Output);
    }

    [Fact]
    public void A_typescript_file_above_the_limit_is_a_blocking_violation()
    {
        var source = Lines(9, line => $"// reason {line}")
            + "/** contract */ export const value = 1; // reason\n"
            + Lines(100, line => $"export const value{line} = {line};");
        using var repository = Fixtures.Compliant().WriteFile("web/src/model.ts", source).Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", TypeScript);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("web/src/model.ts"), run.Output);
        Assert.True(run.OutputContains("10 of 110 authored physical lines"), run.Output);
    }

    [Fact]
    public void Comment_shapes_inside_typescript_literals_do_not_count()
    {
        var source = Lines(10, line => $"const url{line} = 'http://host/{line}'; // reason")
            + Lines(20, line => $"const pattern{line} = /\\/\\/{line}/g;")
            + Lines(20, line => $"const text{line} = `/* ${{value{line}}} */ // not`;")
            + "const wide = `\n// still inside the template\n\n// and here\n`;\n"
            + Lines(70, line => $"const value{line} = total / count{line} / 2;");
        using var repository = Fixtures.Compliant(Frame.AllPresent().Settings(
                """{ "comments.typescript": { "percentageLimit": 7, "minimumCommentLines": 10 } }"""))
            .WriteFile("web/src/literals.tsx", source)
            .Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", TypeScript);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("10 of 124 authored physical lines"), run.Output);
    }

    [Fact]
    public void Declaration_files_and_generated_bundles_are_excluded()
    {
        var dense = Lines(20, line => $"// reason {line}") + "export const value = 1;\n";
        using var repository = Fixtures.Compliant()
            .WriteFile("web/types.d.ts", dense)
            .WriteFile("web/dist/app.js", dense)
            .WriteFile("web/vendor.min.js", dense)
            .WriteFile("web/api.ts", "/* @generated by the contract build */\n" + dense)
            .Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", TypeScript);

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("not applicable"), run.Output);
    }

    [Fact]
    public void Each_language_reads_its_own_settings_section()
    {
        var source = Lines(12, line => $"# reason {line}") + Lines(30, line => $"key{line}: value");
        using var repository = Fixtures.Compliant(Frame.AllPresent().Settings(
                """{ "comments.yaml": { "percentageLimit": 30, "minimumCommentLines": 10 } }"""))
            .WriteFile("deploy/values.yml", source)
            .Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Yaml);

        Assert.Equal(0, run.ExitCode);
    }

    [Fact]
    public void Explain_names_the_reader_and_the_settings_of_each_language()
    {
        using var repository = Fixtures.Compliant();

        var yaml = HarnessCli.Run(repository.Path, "explain", Yaml);
        var typescript = HarnessCli.Run(repository.Path, "explain", TypeScript);

        Assert.Equal(0, yaml.ExitCode);
        Assert.True(yaml.OutputContains("block scalar"), yaml.Output);
        Assert.True(yaml.OutputContains("settings.comments.yaml"), yaml.Output);
        Assert.Equal(0, typescript.ExitCode);
        Assert.True(typescript.OutputContains(".d.ts"), typescript.Output);
        Assert.True(typescript.OutputContains("settings.comments.typescript"), typescript.Output);
    }

    private static string Lines(int count, Func<int, string> line)
        => string.Concat(Enumerable.Range(1, count).Select(number => line(number) + "\n"));
}
