using System.Text.Json;

namespace Harness.Tests;

/// <summary>
/// The Go axis of contract 3.1 (ADR-0055): comment density, cross-file repetition, the package
/// DSM and lint suppressions, each read through the compiled CLI on a fixture repository.
/// </summary>
public sealed class GoLanguageTests
{
    private const string Comments = "comments.go";

    private const string Duplication = "duplication.go";

    private const string Complexity = "complexity.go";

    private const string LintSuppressions = "lint-suppressions.go";

    private const string GoModule = "module example.com/app\n\ngo 1.25\n";

    [Fact]
    public void A_repository_without_go_sources_is_not_applicable_to_every_go_check()
    {
        using var repository = Fixtures.Compliant();

        foreach (var check in new[] { Comments, Duplication, Complexity, LintSuppressions })
        {
            var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", check);

            Assert.Equal(0, run.ExitCode);
            Assert.True(run.OutputContains("not applicable"), run.Output);
        }
    }

    [Fact]
    public void Prose_inside_a_function_above_the_limit_is_a_blocking_violation()
    {
        var source = "package sample\n\nfunc Run() int {\n"
            + Lines(12, line => $"\t// reason {line}")
            + "\ttotal := 0\n"
            + Lines(100, line => $"\ttotal += {line}")
            + "\treturn total\n}\n";
        using var repository = Fixtures.Compliant().WriteFile("internal/sample/run.go", source).Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Comments);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("internal/sample/run.go"), run.Output);
        Assert.True(run.OutputContains("12 of 117 authored physical lines"), run.Output);
    }

    [Fact]
    public void Doc_comments_directives_raw_strings_generated_vendor_and_testdata_do_not_count()
    {
        var authored = "package sample\n\n"
            + Lines(20, line => $"// Run documents itself on line {line}.")
            + "func Run() string {\n\traw := `\n" + Lines(20, line => $"// inside the raw string {line}") + "`\n\treturn raw\n}\n\n"
            + "//go:generate stringer -type=Kind\n"
            + Lines(5, line => $"// Kind is documented on line {line}.")
            + "type Kind int\n";
        var dense = "package other\n\n" + "func Dense() {\n" + Lines(40, line => $"\t// prose {line}") + "}\n";
        using var repository = Fixtures.Compliant()
            .WriteFile("internal/sample/run.go", authored)
            .WriteFile("internal/gen/gen.go", "// Code generated by stringer; DO NOT EDIT.\n\n" + dense)
            .WriteFile("internal/sample/testdata/fixture.go", dense)
            .WriteFile("vendor/dep/dep.go", dense)
            .WriteFile("_tools/tool.go", dense)
            .Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Comments);

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("outcome: passed"), run.Output);
    }

    [Fact]
    public void A_block_repeated_across_files_with_other_names_is_reported_once_with_both_places()
    {
        using var repository = Fixtures.Compliant()
            .WriteFile("internal/first/build.go", Chain("first", "Build", "v"))
            .WriteFile("internal/second/assemble.go", Chain("second", "Assemble", "w"))
            .Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Duplication);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("normalized lines"), run.Output);
        Assert.True(run.OutputContains("internal/first/build.go:"), run.Output);
        Assert.True(run.OutputContains("internal/second/assemble.go:"), run.Output);
    }

    [Fact]
    public void The_package_graph_is_measured_whole_with_the_main_package_as_composition_root()
    {
        using var repository = Packages();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Complexity);

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("limits: average reachable packages 8.00 packages · largest cyclic group size 0 packages"), run.Output);
        Assert.True(run.OutputContains("average reachable packages: 2.80 packages (14 reachable package pairs / 5 packages"), run.Output);
        Assert.True(run.OutputContains("largest cyclic group size: 0 packages (0.00% of 5 packages)"), run.Output);
        Assert.True(run.OutputContains("scope: 5 authored packages of the tracked go.mod modules (test files are not read; 1 main package [cmd/app] is the composition root)"), run.Output);
    }

    [Fact]
    public void Exceeding_the_declared_ceiling_names_the_hubs_but_never_the_main_package()
    {
        using var repository = Packages(Frame.AllPresent().Settings(
            """{ "complexity.go": { "averageReachableFiles": 2.0, "largestCyclicGroupSize": 0 } }"""));

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Complexity);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("average reachable packages 2.80 packages exceeds the 2.00 packages the standard allows"), run.Output);
        Assert.True(run.OutputContains("internal/p1: Dependencies from here reach 4 of 5 packages."), run.Output);
        Assert.False(run.OutputContains("cmd/app: Dependencies"), run.Output);
    }

    [Fact]
    public void A_go_mod_left_out_of_the_index_makes_the_dsm_incomplete_and_is_named()
    {
        using var repository = Fixtures.Compliant()
            .WriteFile("internal/p1/p1.go", "package p1\n\nfunc One() int { return 1 }\n")
            .Commit()
            .WriteFile("go.mod", GoModule);

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", Complexity);

        Assert.Equal(2, run.ExitCode);
        Assert.True(run.OutputContains("no tracked go.mod names a module path"), run.Output);
        Assert.True(run.OutputContains("not in the index  go.mod"), run.Output);
    }

    [Fact]
    public void Nolint_without_linters_or_without_a_reason_is_blocking_and_a_justified_one_passes()
    {
        var source = "package sample\n\nfunc Run() {\n"
            + "\t_ = f() //nolint:errcheck\n"
            + "\t_ = f() //nolint\n"
            + "\t_ = f() //nolint:all // reason\n"
            + "\t_ = f() //nolint:gosec,errcheck // closing a read-only file\n"
            + "\t// nolint is discussed in prose here\n"
            + "}\n\nfunc f() error { return nil }\n";
        using var repository = Fixtures.Compliant().WriteFile("internal/sample/run.go", source).Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", LintSuppressions);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("internal/sample/run.go:4: silences errcheck via //nolint:errcheck without a reason"), run.Output);
        Assert.True(run.OutputContains("internal/sample/run.go:5: silences every linter via //nolint;"), run.Output);
        Assert.True(run.OutputContains("internal/sample/run.go:6: silences every linter via //nolint:all;"), run.Output);
        Assert.False(run.OutputContains("run.go:7"), run.Output);
        Assert.False(run.OutputContains("run.go:8"), run.Output);
    }

    [Fact]
    public void A_v1_yaml_configuration_prints_repository_wide_switches_and_blocks_a_path_scoped_rule()
    {
        const string config = "linters:\n  disable-all: true\n  disable: [gosec]\nissues:\n  exclude-rules:\n"
            + "    - path: _test\\.go\n      linters:\n        - gosec\n"
            + "    - linters: [errcheck]\n      text: \"Close\"\n"
            + "    - path: internal/legacy/\n";
        using var repository = Fixtures.Compliant()
            .WriteFile("internal/sample/run.go", "package sample\n\nfunc Run() {}\n")
            .WriteFile(".golangci.yml", config)
            .Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", LintSuppressions);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("every linter is switched off repository-wide via linters.disable-all: true without linters.enable at .golangci.yml:2"), run.Output);
        Assert.True(run.OutputContains("gosec is switched off repository-wide via linters.disable at .golangci.yml:3"), run.Output);
        Assert.True(run.OutputContains(".golangci.yml:6: silences gosec for path `_test\\.go` via issues.exclude-rules at one address"), run.Output);
        Assert.True(run.OutputContains("issues.exclude-rules at .golangci.yml:9 excludes errcheck matching text \"Close\" repository-wide, without a path"), run.Output);
        Assert.True(run.OutputContains("issues.exclude-rules at .golangci.yml:11 excludes every linter repository-wide, for path `internal/legacy/`"), run.Output);
    }

    [Fact]
    public void A_v2_yaml_configuration_reads_default_none_and_exclusions_rules()
    {
        const string config = "version: \"2\"\nlinters:\n  default: none\n  exclusions:\n    rules:\n"
            + "      - path: internal/legacy/\n        linters: [staticcheck]\n"
            + "      - path: .*\n        text: \"should have comment\"\n";
        using var repository = Fixtures.Compliant()
            .WriteFile("internal/sample/run.go", "package sample\n\nfunc Run() {}\n")
            .WriteFile(".golangci.yaml", config)
            .Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", LintSuppressions);

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("every linter is switched off repository-wide via linters.default: none without linters.enable at .golangci.yaml:3"), run.Output);
        Assert.True(run.OutputContains(".golangci.yaml:6: silences staticcheck for path `internal/legacy/` via linters.exclusions.rules at one address"), run.Output);
        Assert.True(run.OutputContains("linters.exclusions.rules at .golangci.yaml:8 excludes every linter matching text \"should have comment\" repository-wide, for path `.*`"), run.Output);
    }

    [Fact]
    public void Toml_and_json_configurations_are_read_by_tables_and_by_the_bcl()
    {
        const string toml = "[linters]\ndisable-all = true\nenable = [\"errcheck\"]\n\n[[issues.exclude-rules]]\npath = \"_test\\\\.go\"\nlinters = [\"gosec\"]\n";
        const string json = """{ "linters": { "disable-all": true }, "issues": { "exclude-rules": [ { "path": ".", "linters": ["errcheck"] } ] } }""";
        using var withToml = Fixtures.Compliant()
            .WriteFile("internal/sample/run.go", "package sample\n\nfunc Run() {}\n")
            .WriteFile(".golangci.toml", toml)
            .Commit();
        using var withJson = Fixtures.Compliant()
            .WriteFile("internal/sample/run.go", "package sample\n\nfunc Run() {}\n")
            .WriteFile(".golangci.json", json)
            .Commit();

        var tomlRun = HarnessCli.RunVerbose(withToml.Path, "check", "--only", LintSuppressions);
        var jsonRun = HarnessCli.RunVerbose(withJson.Path, "check", "--only", LintSuppressions);

        Assert.Equal(1, tomlRun.ExitCode);
        Assert.False(tomlRun.OutputContains("disable-all"), tomlRun.Output);
        Assert.True(tomlRun.OutputContains(".golangci.toml:5: silences gosec for path `_test\\.go` via issues.exclude-rules at one address"), tomlRun.Output);
        Assert.Equal(0, jsonRun.ExitCode);
        Assert.True(jsonRun.OutputContains("every linter is switched off repository-wide via linters.disable-all: true without linters.enable at .golangci.json"), jsonRun.Output);
        Assert.True(jsonRun.OutputContains("issues.exclude-rules at .golangci.json excludes errcheck repository-wide, for path `.`"), jsonRun.Output);
    }

    [Fact]
    public void Init_on_a_go_repository_writes_the_go_sections_and_the_vet_and_gofmt_hint()
    {
        using var repository = RepositoryFixture.CreateGitRepository()
            .WriteFile("go.mod", GoModule)
            .WriteFile("cmd/app/main.go", "package main\n\nfunc main() {}\n")
            .Commit();

        var run = HarnessCli.Run(repository.Path, "init");

        Assert.Equal(0, run.ExitCode);
        Assert.Contains("Declared go from the tracked sources", run.StandardOutput, StringComparison.Ordinal);
        Assert.Contains("`go vet ./...`", run.StandardOutput, StringComparison.Ordinal);
        Assert.Contains("`gofmt -l`", run.StandardOutput, StringComparison.Ordinal);
        Assert.False(File.Exists(repository.Absolute(".editorconfig")));

        using var document = JsonDocument.Parse(File.ReadAllText(repository.Absolute(".harness.json")));
        var root = document.RootElement;
        Assert.False(root.TryGetProperty("architecture", out _));
        Assert.Equal(["go"], root.GetProperty("applicability").EnumerateObject().Select(axis => axis.Name));
        Assert.Equal(
            ["complexity.go", "comments.go", "duplication.go", "commits"],
            root.GetProperty("settings").EnumerateObject().Select(section => section.Name));
        Assert.Equal(8.0, root.GetProperty("settings").GetProperty("complexity.go").GetProperty("averageReachableFiles").GetDouble());
        Assert.Equal(30, root.GetProperty("settings").GetProperty("duplication.go").GetProperty("windowLines").GetInt32());
        Assert.Equal("required", root.GetProperty("policy").GetProperty("lint-suppressions.go").GetString());
        Assert.False(root.GetProperty("policy").TryGetProperty("comments.csharp", out _));
    }

    [Fact]
    public void Coverage_prints_the_go_fragment_for_an_undeclared_go_axis()
    {
        const string frame = """
            {
              "version": "latest",
              "settings": { "commits": { "language": "ru", "requireSetup": false } },
              "policy": { "harness.coverage": "required" }
            }
            """;
        using var repository = Fixtures.WithRawFrame(frame)
            .WriteFile("cmd/app/main.go", "package main\n\nfunc main() {}\n")
            .Commit();

        var run = HarnessCli.RunVerbose(repository.Path, "check", "--only", "harness.coverage");

        Assert.Equal(1, run.ExitCode);
        Assert.True(run.OutputContains("1 tracked Go source (cmd/app/main.go) but no `applicability.go` entry"), run.Output);
        Assert.True(run.OutputContains("\"go\": { \"applicable\": true }"), run.Output);
        Assert.True(run.OutputContains("\"complexity.go\": {"), run.Output);
        Assert.True(run.OutputContains("\"lint-suppressions.go\": \"required\""), run.Output);
    }

    [Fact]
    public void Explain_describes_each_go_check_in_its_own_terms()
    {
        using var repository = Fixtures.Compliant();

        var comments = HarnessCli.Run(repository.Path, "explain", Comments);
        var duplication = HarnessCli.Run(repository.Path, "explain", Duplication);
        var complexity = HarnessCli.Run(repository.Path, "explain", Complexity);
        var suppressions = HarnessCli.Run(repository.Path, "explain", LintSuppressions);

        Assert.Equal(0, comments.ExitCode);
        Assert.True(comments.OutputContains("DO NOT EDIT") && comments.OutputContains("settings.comments.go"), comments.Output);
        Assert.Equal(0, duplication.ExitCode);
        Assert.True(duplication.OutputContains("predeclared") && duplication.OutputContains("settings.duplication.go"), duplication.Output);
        Assert.Equal(0, complexity.ExitCode);
        Assert.True(complexity.OutputContains("settings.complexity.go") && complexity.OutputContains("refuses an import cycle"), complexity.Output);
        Assert.Equal(0, suppressions.ExitCode);
        Assert.True(suppressions.OutputContains("//nolint:errcheck // reason") && suppressions.OutputContains("linters.default"), suppressions.Output);
    }

    /// <summary>main → p1 → {p2, p3} → p4: reaches 5 + 4 + 2 + 2 + 1 = 14 over 5 packages.</summary>
    private static RepositoryFixture Packages(Frame? frame = null)
        => Fixtures.Compliant(frame ?? Frame.AllPresent())
            .WriteFile("go.mod", GoModule)
            .WriteFile("cmd/app/main.go", "package main\n\nimport \"example.com/app/internal/p1\"\n\nfunc main() { _ = p1.One() }\n")
            .WriteFile("internal/p1/p1.go", "package p1\n\nimport (\n\t\"example.com/app/internal/p2\"\n\t\"example.com/app/internal/p3\"\n)\n\nfunc One() int { return p2.Two() + p3.Three() }\n")
            .WriteFile("internal/p2/p2.go", "package p2\n\nimport \"example.com/app/internal/p4\"\n\nfunc Two() int { return p4.Four() }\n")
            .WriteFile("internal/p3/p3.go", "package p3\n\nimport \"example.com/app/internal/p4\"\n\nfunc Three() int { return p4.Four() }\n")
            .WriteFile("internal/p3/p3_test.go", "package p3\n\nimport \"example.com/app/cmd/app\"\n")
            .WriteFile("internal/p4/p4.go", "package p4\n\nfunc Four() int { return 4 }\n")
            .Commit();

    private static string Chain(string package, string function, string variable)
        => $"package {package}\n\nfunc {function}(x int) int {{\n\t{variable}0 := x\n"
            + Lines(34, line => $"\t{variable}{line} := {variable}{line - 1} + {line}")
            + $"\treturn {variable}34\n}}\n";

    private static string Lines(int count, Func<int, string> line)
        => string.Concat(Enumerable.Range(1, count).Select(number => line(number) + "\n"));
}
