namespace Harness.Tests;

/// <summary>The frame file: complete answers, policy and named exceptions.</summary>
public sealed class HarnessFrameTests
{
    [Fact]
    public void A_repository_without_a_frame_cannot_be_verified()
    {
        using var repository = Fixtures.WithoutAFrame();

        var run = HarnessCli.Run(repository.Path, "check");

        Assert.Equal(2, run.ExitCode);
        Assert.True(run.OutputContains("INCOMPLETE"), run.Output);
        Assert.True(run.OutputContains(".harness.json"), run.Output);
        Assert.True(run.OutputContains("\"answers\""), run.Output);
    }

    [Fact]
    public void An_untracked_frame_does_not_count()
    {
        using var repository = Fixtures.WithoutAFrame()
            .WriteFile(".harness.json", Frame.Answering().ToString());

        var run = HarnessCli.Run(repository.Path, "check");

        Assert.Equal(2, run.ExitCode);
        Assert.True(run.OutputContains("is not tracked"), run.Output);
    }

    [Theory]
    [InlineData("{ not json", "not readable as JSON")]
    [InlineData("[]", "not a JSON object")]
    [InlineData("{}", "'version' must be 2")]
    [InlineData("""{ "version": 1 }""", "'version' must be 2")]
    [InlineData("""{ "version": 2, "answers": [] }""", "'answers' must be an object")]
    [InlineData("""{ "version": 2, "checks": {} }""", "not a key this harness reads")]
    [InlineData("""{ "version": 2, "answers": { "tests": {} } }""", "not a question this harness asks")]
    [InlineData("""{ "version": 2, "answers": { "format": { "present": true } } }""", "needs a non-empty 'reason'")]
    [InlineData("""{ "version": 2, "answers": { "format": { "paths": [] } } }""", "is empty")]
    [InlineData("""{ "version": 2, "answers": { "format": { "paths": [".x"], "present": true } } }""", "already an answer")]
    [InlineData("""{ "version": 2, "answers": { "format": { "applicable": false } } }""", "why the question does not apply")]
    [InlineData("""{ "version": 2, "answers": { "format": { "hint": 1 } } }""", "not a key this harness reads")]
    [InlineData("""{ "version": 2, "answers": {} }""", "does not answer")]
    public void An_unsound_frame_ends_the_run_as_incomplete(string frame, string explanation)
    {
        using var repository = Fixtures.WithRawFrame(frame);

        var run = HarnessCli.Run(repository.Path, "check");

        Assert.Equal(2, run.ExitCode);
        Assert.True(run.OutputContains(explanation), run.Output);
    }

    [Theory]
    [InlineData("docs.plicy", "off", "not a check or group this harness ships")]
    [InlineData("docs.policy", "lenient", "must be required, advisory or off")]
    public void Invalid_policy_ends_the_run_as_incomplete(string selector, string value, string explanation)
    {
        using var repository = Fixtures.WithRawFrame(Frame.Answering().Policy(selector, value).ToString());

        var run = HarnessCli.Run(repository.Path, "check");

        Assert.Equal(2, run.ExitCode);
        Assert.True(run.OutputContains(explanation), run.Output);
    }

    [Theory]
    [InlineData("docs.policy", "ROOT.md", "", "must say why")]
    [InlineData("nope", "ROOT.md", "because", "must name a check")]
    public void Invalid_suppression_ends_the_run_as_incomplete(
        string check,
        string location,
        string reason,
        string explanation)
    {
        using var repository = Fixtures.WithRawFrame(
            Frame.Answering().Suppressing(check, location, reason).ToString());

        var run = HarnessCli.Run(repository.Path, "check");

        Assert.Equal(2, run.ExitCode);
        Assert.True(run.OutputContains(explanation), run.Output);
    }

    [Fact]
    public void A_missing_answer_invalidates_the_whole_frame()
    {
        using var repository = Fixtures.Compliant(Frame.Answering().Silent("tests.unit"));

        var run = HarnessCli.Run(repository.Path, "check");

        Assert.Equal(2, run.ExitCode);
        Assert.True(run.OutputContains("answers.tests.unit"), run.Output);
        Assert.False(run.OutputContains("repository answers absent"), run.Output);
    }

    [Fact]
    public void Required_policy_accepts_a_positive_self_report()
    {
        using var repository = Fixtures.Compliant(
            Frame.Answering()
                .Present("tests.unit", "the suite is generated by the build")
                .Policy("frame.tests.unit", "required"));

        var run = HarnessCli.Run(repository.Path, "check", "--only", "frame.tests.unit");

        Assert.Equal(0, run.ExitCode);
    }

    [Fact]
    public void A_check_identifier_outranks_its_group_in_policy()
    {
        using var repository = Fixtures.Compliant(
            Frame.Answering()
                .Policy("frame", "required")
                .Policy("frame.tests.unit", "off"));

        var run = HarnessCli.Run(repository.Path, "check", "--only", "frame.tests.unit");

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("turns this check off"), run.Output);
    }

    [Fact]
    public void A_check_turned_off_does_not_run_but_stays_visible()
    {
        using var repository = Fixtures.Compliant(Frame.Answering().Policy("docs.policy", "off"))
            .WriteLines("ROOT.md", 400)
            .Commit();

        var run = HarnessCli.Run(repository.Path, "check");

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("skipped"), run.Output);
        Assert.True(run.OutputContains("docs.policy"), run.Output);
    }

    [Fact]
    public void A_named_exception_clears_a_violation_and_stays_on_the_report()
    {
        using var repository = Fixtures
            .Compliant(Frame.Answering().Suppressing("docs.policy", "ROOT.md", "split in IDP-142"))
            .WriteLines("ROOT.md", 400)
            .Commit();

        var run = HarnessCli.Run(repository.Path, "check", "--only", "docs.policy");

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("suppressed"), run.Output);
        Assert.True(run.OutputContains("split in IDP-142"), run.Output);
    }

    [Fact]
    public void An_exception_that_matched_nothing_is_reported_on_the_frame()
    {
        using var repository = Fixtures.Compliant(
            Frame.Answering().Suppressing("docs.policy", "gone.md", "was fixed last quarter"));

        var run = HarnessCli.Run(repository.Path, "check");

        Assert.Equal(0, run.ExitCode);
        Assert.True(run.OutputContains("matched nothing in this run"), run.Output);
        Assert.True(run.OutputContains("was fixed last quarter"), run.Output);
    }

    [Fact]
    public void Reading_the_frame_does_not_modify_the_repository()
    {
        using var repository = Fixtures.Compliant(
            Frame.Answering().Policy("frame", "required").Suppressing("docs.policy", "ROOT.md", "why not"));

        var before = repository.TrackedState();

        HarnessCli.Run(repository.Path, "check");

        Assert.Equal(before, repository.TrackedState());
    }
}
