<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>harness</AssemblyName>
    <RootNamespace>Harness</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

</Project>
