using Harness.Languages;

namespace Harness.Checks.Comments;

internal static class CommentLineExplanation
{
    public static string For(Language language)
        => Rationale + Rule + Warranted + Evidence(language) + Limits(language) + Remediation;

    private const string Rationale =
        """
        Rationale
          Comments are useful when they preserve information the code cannot express. They
          become a parallel narrative when they restate names and control flow, and that
          narrative can drift while the compiler keeps accepting the code. A density limit
          makes comment-heavy files blocking and asks for deliberate review; it does not
          claim that every comment below the limit is useful.


        """;

    private const string Rule =
        """
        Rule
          A file violates the rule when it reaches the configured `minimumCommentLines` and
          comments exceed the configured `percentageLimit` of authored physical lines. An authored
          line is a non-empty line carrying code, a string continuation or a comment. A line
          carrying both code and a comment appears once in the denominator and once in the
          comment numerator.

          A physical line is counted once when any part of a comment occurs on it. Inline
          comments and documentation comments count. Comment-shaped text inside a literal
          does not count.


        """;

    private const string Warranted =
        """
        When a comment is warranted
          Keep a comment only when the code alone cannot make one of these clear:
          - the reason for a non-obvious decision or constraint;
          - an important invariant;
          - a workaround, with its source or removal condition;
          - a public API contract when the language or repository convention requires it.

          Express everything else in names and structure: a retelling of the code, a doc
          comment that repeats a function or key name, narration, decorative separators,
          commented-out code, and a TODO without a concrete issue are not durable context.


        """;

    private const string Remediation =
        """
        Remediation
          Review the reported file. Delete stale, obvious and decorative prose; remove
          commented-out code; and link each TODO to a concrete task. If names and structure
          can carry the meaning, refactor names and structure instead of adding a comment.
          Keep concise comments that preserve non-obvious reasons, invariants, sourced
          workarounds or required API contracts.

        """;

    private static string Evidence(Language language)
    {
        var read = language == Language.CSharp
            ? """
              The check reads Git-tracked `.cs` files through the shared lexical C# reader.
              Generated, vendored and build-output locations, generated file-name suffixes and
              files carrying an `<auto-generated>` marker are excluded. A `//`, `///` or
              `/* ... */` comment counts.
            """
            : language == Language.Yaml
                ? """
              The check reads Git-tracked `.yml` and `.yaml` files outside generated, vendored
              and build-output locations. A `#` at the start of a line or after whitespace
              counts; a `#` inside a quoted scalar or a `|`/`>` block scalar is content.
            """
                : """
              The check reads Git-tracked `.ts`, `.tsx`, `.mts`, `.cts`, `.js`, `.jsx`, `.mjs`
              and `.cjs` files outside generated, vendored and build-output locations.
              Declaration files (`.d.ts`), minified bundles (`.min.js`) and files carrying an
              `@generated` or `<auto-generated>` marker are excluded. A `//` or `/* ... */`
              comment counts, including JSDoc.
            """;

        return "Evidence\n" + read + "\n"
            + """
              Unreadable evidence makes the check incomplete rather than shortening the count
              silently.


            """;
    }

    private static string Limits(Language language)
    {
        var lexical = language == Language.CSharp
            ? """
              Comments inside interpolation holes are covered by the containing string region
              and are not counted; a preprocessor directive line is masked as one directive,
              including any trailing comment.
            """
            : language == Language.Yaml
                ? """
              Block scalar content is recognised by indentation deeper than the line that
              opened it; a plain multi-line scalar that happens to contain ` #` reads as a
              comment, which is also how YAML reads it.
            """
                : """
              A regular expression literal is told from division by the token before it, so an
              unusual layout can hide a comment inside a literal or count a literal as a
              comment on one line. JSX text is read as code, not as a literal.
            """;

        return "Limits\n"
            + """
              This is a lexical count, not a judgement of whether prose is true or valuable.

            """
            + lexical + "\n"
            + $"""
              Both values live under `settings.{language.Qualify("comments")}` in `.harness.json`;
              they are repository policy, not industry constants. A file with an unusually
              dense set of indispensable comments can use `policy.{language.Qualify("comments")}`.


            """;
    }
}
