using Harness.Languages;

namespace Harness.Checks.Comments;

internal static class CommentLineExplanation
{
    public static string For(Language language)
        => Rationale + Rule + Warranted + Evidence(language) + Limits(language) + Remediation;

    private const string Rationale =
        """
        Rationale
          Comments are useful when they preserve information the code cannot express. They
          become a parallel narrative when they restate names and control flow, and that
          narrative can drift while the compiler keeps accepting the code. A density limit
          makes comment-heavy files blocking and asks for deliberate review; it does not
          claim that every comment below the limit is useful.


        """;

    private const string Rule =
        """
        Rule
          A file violates the rule when it reaches the configured `minimumCommentLines` and
          comments exceed the configured `percentageLimit` of authored physical lines. An authored
          line is a non-empty line carrying code, a string continuation or a comment. A line
          carrying both code and a comment appears once in the denominator and once in the
          comment numerator.

          A physical line is counted once when any part of a comment occurs on it. Inline
          comments and documentation comments count unless the language-specific Evidence
          below excludes them. Comment-shaped text inside a literal
          does not count.


        """;

    private const string Warranted =
        """
        When a comment is warranted
          Keep a comment only when the code alone cannot make one of these clear:
          - the reason for a non-obvious decision or constraint;
          - an important invariant;
          - a workaround, with its source or removal condition;
          - a public API contract when the language or repository convention requires it.

          Express everything else in names and structure: a retelling of the code, a doc
          comment that repeats a function or key name, narration, decorative separators,
          commented-out code, and a TODO without a concrete issue are not durable context.


        """;

    private const string Remediation =
        """
        Remediation
          Review the reported file. Delete stale, obvious and decorative prose; remove
          commented-out code; and link each TODO to a concrete task. If names and structure
          can carry the meaning, refactor names and structure instead of adding a comment.
          Keep concise comments that preserve non-obvious reasons, invariants, sourced
          workarounds or required API contracts.

        """;

    private static string Evidence(Language language)
    {
        var read = language == Language.CSharp
            ? """
              The check reads Git-tracked `.cs` files through the shared lexical C# reader.
              A generated suffix or `<auto-generated>` marker excludes a file only under a
              declared `generated` path. A `//`, `///` or
              `/* ... */` comment counts.
            """
            : language == Language.Yaml
                ? """
              The check reads Git-tracked `.yml` and `.yaml` files outside declared generated
              and toolchain-ignored paths. A `#` at the start of a line or after whitespace is a
              comment; a `#` inside a quoted scalar or a `|`/`>` block scalar is content. A
              block of comment lines whose next non-empty line is a mapping key, a `- ` item —
              at any depth — or `---` documents that key and leaves both counts, as a Go doc
              comment does; blank lines between the block and the key are allowed. A trailing
              comment on a line with a value documents that value and is not counted. A
              directive — `# yamllint`, `# noqa`, `# ansible-lint` — leaves both counts. What counts is
              prose: a block followed by another block, or by the end of the file.
            """
                : language == Language.Go
                ? """
              The check reads Git-tracked `.go` files, test files included. Go `vendor/` and
              `testdata/` directories and directories starting with `_` or `.` are ignored by
              the toolchain. A `Code generated ... DO NOT EDIT.` header excludes a file only
              under a declared path;
              `//go:build ignore` (or `// +build ignore`) excludes it by Go semantics. A `//` or
              `/* ... */` comment outside a string, raw string or rune
              literal counts. A directive — `//go:build`, `//go:embed`, `//go:generate`,
              `//line`, `//export`, `//extern`, `//nolint`, `//lint:` — is an instruction to
              a tool and counts as code. The doc comment of a top-level declaration — the
              comment lines directly above a line starting in column 0 with `func`, `type`,
              `var`, `const`, `import` or `package` — is the language's own convention for
              exported identifiers and leaves both counts.
            """
                : """
              The check reads Git-tracked `.ts`, `.tsx`, `.mts`, `.cts`, `.js`, `.jsx`, `.mjs`
              and `.cjs` files. Declaration files (`.d.ts`) are toolchain-ignored; minified bundles
              (`.min.js`) and `@generated` or `<auto-generated>` markers exclude files only under
              declared `generated` paths. A `//` or `/* ... */`
              comment counts, including JSDoc.
            """;

        return "Evidence\n" + read + "\n"
            + """
              Unreadable evidence makes the check incomplete rather than shortening the count
              silently.


            """;
    }

    private static string Limits(Language language)
    {
        var lexical = language == Language.CSharp
            ? """
              Comments inside interpolation holes are covered by the containing string region
              and are not counted; a preprocessor directive line is masked as one directive,
              including any trailing comment.
            """
            : language == Language.Yaml
                ? """
              Documentation is told by position, not by content: commented-out configuration
              directly above a key passes as documentation, and a block that restates the key's
              name is not caught. The limit measures the prose no key follows — a header
              paragraph, a commented-out play between two paragraphs, a closing note. Block
              scalar content is recognised by indentation deeper than the line that opened it;
              a plain multi-line scalar that happens to contain ` #` reads as a comment, which
              is also how YAML reads it.
            """
                : language == Language.Go
                ? """
              Doc comments are told by position, not by the exported name they describe: a
              comment block directly above any top-level declaration leaves the count, and a
              comment inside a function body or beside a field counts. So the limit measures
              prose inside the code, not the documentation the language asks for, and the
              default 10/8 profile stays; `golint`-style one-line doc stubs are outside it.
              Build constraints are not evaluated, and a raw string spanning lines carries
              content on every line, so text inside one never counts.
            """
                : """
              A regular expression literal is told from division by the token before it, so an
              unusual layout can hide a comment inside a literal or count a literal as a
              comment on one line. JSX text is read as code, not as a literal.
            """;

        return "Limits\n"
            + """
              This is a lexical count, not a judgement of whether prose is true or valuable.

            """
            + lexical + "\n"
            + $"""
              Both values live under `settings.{language.Qualify("comments")}` in `.harness.json`;
              they are repository policy, not industry constants. A file with an unusually
              dense set of indispensable comments can use `policy.{language.Qualify("comments")}`.


            """;
    }
}
