namespace Harness.Checks.Dependencies;

/// <summary>Long-form content for `harness explain dependencies.csharp`.</summary>
internal static class DependenciesExplanation
{
    public const string Text =
        """
        Rationale
          Modules that depend on each other cannot be ordered, moved or reused in one
          direction. That is a universal structural defect the harness can prove from
          tracked source. Raw dependency counts are different: a test, composition root or
          stable abstraction may correctly know or be known by many types. The current check
          therefore reports cycles and does not report fan-in or fan-out.

        Discovery
          Every Git-tracked `.cs` file is read. Generated, vendored and build-output
          locations are excluded, as are files named `*.g.cs`, `*.generated.cs` and
          `*.Designer.cs`, and files whose first five lines carry the `<auto-generated>`
          marker. The harness does not build the repository or read compiler output.

        Resolution
          Each declared type is indexed by its simple name. A name is attributed to a
          declaration when exactly one candidate remains after considering its namespace,
          enclosing namespaces and imports. An ambiguous name is left out of the graph.

        Evidence
          A cycle uses only `Proven` references: the name stands where C# allows nothing but
          a type, such as a construction, base list, parameter, field, property, return type,
          generic argument, attribute, `typeof`, `sizeof`, `default` or `catch`. Member
          accesses, arguments and other name matches are `Inferred` and cannot close a cycle.

        Formula
          A module dependency cycle is a set of namespaces that all reach each other through
          proven references between their declared types. A namespace and its nested
          namespace are one module boundary here, not a dependency cycle.

        Why a cycle is blocking
          Every reported edge stands in a type-only position and resolves to one declaration.
          The cycle has no valid dependency order, so required policy treats it as a
          violation. The report names the shortest ring and the source lines that close it.

        What this check deliberately leaves elsewhere
          Repeated test setup belongs to `duplication.csharp`; allowed layer directions belong
          to the repository's semantic architecture tests. Type size, member groups and raw
          incoming or outgoing counts have no universal remediation and are not part of the
          current contract.

        Limits
          Nothing is bound by the compiler. Extension methods, overload resolution, implicit
          conversions, aliases, conditional compilation and reflection are not evaluated.
          A unique internal type with the same simple name as an external type can still be
          resolved incorrectly even in a type-only position. Partial types are merged.

        Policy
          A proved cycle is blocking by default and cannot be suppressed by path. If the
          repository consciously accepts all findings from this check, tracked policy may
          make the whole check `advisory` or `off`; that broader decision stays visible in
          review.

        Remediation
          Read each edge in the reported ring and choose the intended direction. Usually the
          shared concept belongs in a third module that both sides may depend on, or one side
          should accept a smaller contract instead of naming the other module's concrete type.
        """;
}
