namespace Harness.Checks.Complexity;

internal static class ComplexityExplanation
{
    public const string Text =
        """
        Rationale
          A dependency count describes one file. A design structure matrix (DSM) describes
          how a change can propagate through the product as a whole. These measurements
          are compared with one repository-wide, tracked ceiling in `.harness.budget.json`.
          A regression is blocking; an improvement is visible until the repository records
          it. This is tier 2 of contract 2.0: tier 1 fixes topology, tier 2 keeps global DSM
          metrics under a budget, and tier 3 applies explicit deterministic policy. ADR-0032
          defines the model, ADR-0033 fixes the sliced-dotnet/1 vocabulary used by tier 1,
          and ADR-0042 narrows the DSM to the product and replaces propagation cost with
          mean reach.

        Scope
          When `architecture` names sliced-dotnet/1, the DSM measures the files inside the
          architecture zones the shape check discovers: a directory holding Application/
          and the canonical layers below it. Tests, tooling and samples outside a zone are
          not nodes, and an edge into them lends no reachability. This is the same line
          the shape check draws, read from the tree, so no frame answer and no list of
          exclusions can move a file across it. Without a zone — a standalone library or a
          repository that does not follow sliced-dotnet — the product is every authored file
          whose nearest tracked project file is not a test project. A project is a test
          project when its own XML references Microsoft.NET.Test.Sdk, xunit, NUnit, MSTest or
          TUnit, sets IsTestProject, or uses MSTest.Sdk; the report names the test projects
          it left out. Only a repository without any test project is measured whole.

        Discovery
          Every authored, Git-tracked `.cs` file in scope is one node. Generated, vendored
          and build-output files are excluded by the C# source reader. Multiple type
          references between the same two files collapse to one directed file edge.
          Intra-file references do not create an edge.

        Evidence
          Only `Proven` references enter the DSM: the referenced name occurs in a type-only
          C# position and resolves to exactly one authored declaration. `Inferred` references
          are omitted so an uncertain lexical match cannot inflate either measurement.

        Mean reach formula
          Let N be the measured-file count and R(i) contain file i itself plus every file
          transitively reachable from it. Mean reach = sum(|R(i)|) / N, in files: how many
          files a change to a typical file can reach, itself included. The report also
          prints propagation cost = 100 * sum(|R(i)|) / N^2 from MacCormack, Rusnak and
          Baldwin, for comparison with the literature (Linux 5.16%, Mozilla 17.35%, Mozilla
          after redesign 2.78%): https://doi.org/10.1287/mnsc.1060.0552
          Mean reach is the budgeted value because it is an absolute quantity: adding leaf
          files does not shrink it through the N^2 denominator, and removing an isolated
          file moves it by at most a fraction of one file.

        Core size formula
          Collapse the directed file graph into strongly connected components. Core size is
          the file count of the largest cyclic component and 100 * core files / N. Singleton
          acyclic components do not form a core, so a DAG reports zero. This follows the
          core-periphery method of Baldwin, MacCormack and Rusnak:
          https://www.sciencedirect.com/science/article/pii/S0048733314001012

        Computation
          The SCC condensation is a DAG. Reachability is computed as bit sets in reverse
          topological order, without recursion, reflection, compiler services or external
          dependencies, so the calculation remains compatible with NativeAOT.

        Limits
          The result measures the lexical graph the harness can prove, not runtime calls,
          reflection, generated code or ambiguous names. Missing edges conservatively
          underestimate coupling. A tracked file whose first lines carry an
          `<auto-generated>` marker is not read at all; the report names such files inside
          the scope, because that marker is one line away from any hub file and a reviewer
          should see it. Cross-language file dependencies are not yet represented. Test
          projects are recognised from their own tracked XML without MSBuild evaluation, so a
          marker inherited only through Directory.Build.props is not seen and that project
          stays in the measurement; the `scope:` line makes the decision visible.

        Policy
          A regression is blocking when the tracked policy for this check is required, and no
          file is exempt from the measurement. A repository may run the whole check `advisory`
          or `off`. A missing budget stays incomplete under `advisory`, because an unread
          measurement is not a softened finding; a repository that keeps no budget answers `off`.

        Remediation
          Run `harness budget update` once to create `.harness.budget.json`. Commit both files.
          The budget is a ceiling: a repository may keep it where it is and treat the
          improvement notice as information, or run `harness budget update` to ratchet it
          down to the current value. A rising mean reach means more files lie downstream
          of typical changes. A growing core means more files must change as a mutually
          dependent group; break an edge or extract a lower-level concept. The update
          command only lowers budgets; raising one requires an explicit tracked edit and
          review. A budget written by contract 2.5 records propagationCost and is migrated
          by the same command.

        Decisions
          adrs/0032-topology-over-thresholds.md
          adrs/0033-canonical-standard-over-declarations.md
          adrs/0042-dsm-over-the-product-in-files.md
          adrs/0048-dsm-product-boundary-without-a-zone.md
        """;
}
