using Harness.Structure;

namespace Harness.Checks.Complexity;

/// <summary>
/// Which files the DSM measures. Inside a sliced-dotnet repository that is the product: the
/// files under its architecture zones. Tests, tooling and samples outside the zones still
/// exist in the graph the language read, but an edge into them lends no reachability here.
/// A repository without a zone is measured whole, because nothing marks its product apart.
/// </summary>
internal sealed record DsmScope(SourceGraph Graph, IReadOnlyList<string> Zones, int OutsideFiles)
{
    public static DsmScope Of(SourceGraph graph, bool architectureApplicable, IReadOnlyList<string> trackedPaths)
    {
        var zones = architectureApplicable ? ArchitectureZones.Discover(trackedPaths) : [];
        if (zones.Count == 0)
        {
            return new DsmScope(graph, [], 0);
        }

        var inside = graph.Within(path => ArchitectureZones.Contains(zones, path));
        return new DsmScope(inside, zones, graph.SourcePaths.Count - inside.SourcePaths.Count);
    }

    public string Describe()
    {
        var measured = Graph.SourcePaths.Count;
        if (Zones.Count == 0)
        {
            return $"scope: {measured} authored files (no architecture zone; the repository is measured whole)";
        }

        var zoneList = string.Join(", ", Zones.Select(ArchitectureZones.Display));
        var outside = OutsideFiles == 1
            ? "1 authored file outside the zones is not measured"
            : $"{OutsideFiles} authored files outside the zones are not measured";
        return $"scope: {measured} files inside architecture zone{(Zones.Count == 1 ? "" : "s")} [{zoneList}]; {outside}";
    }

    public string? DescribeMarkedGenerated()
    {
        var count = Graph.MarkedGenerated.Count;
        if (count == 0)
        {
            return null;
        }

        var files = count == 1
            ? "1 tracked C# file with an <auto-generated> header is not read"
            : $"{count} tracked C# files with an <auto-generated> header are not read";
        return $"generated markers: {files}: "
            + string.Join(", ", Graph.MarkedGenerated.Take(5))
            + (count > 5 ? $", and {count - 5} more" : "");
    }
}
