namespace Harness.Checks.Dependencies;

/// <summary>Long-form content for `harness explain dependencies.csharp`.</summary>
internal static class DependenciesExplanation
{
    public const string Text =
        """
        Rationale
          Coupling is the property that decides whether a part of a repository can be read,
          changed, moved or reused on its own. It is also the property most often claimed
          and least often measured: a count of import lines is not coupling, and a number
          without a named formula behind it is not evidence. This check builds the graph the
          repository declares about itself and reports it, separating what it can prove from
          what it can only suggest.

        Discovery
          Every Git-tracked `.cs` file is read. Generated, vendored and build-output
          locations are excluded, as are files named `*.g.cs`, `*.generated.cs` and
          `*.Designer.cs`, and files whose first five lines carry the `<auto-generated>`
          marker. The harness does not build the repository and does not read its build
          output, so nothing here comes from a compiler.

        Resolution
          The types a repository declares are a closed vocabulary, and that is what makes
          resolution possible without one. Each declared type is indexed by its simple name.
          A name in a file is attributed to a declaration when exactly one candidate remains
          after applying the order C# itself uses: the namespace the reference is written
          in, then the namespaces that enclose it, then what the file imports. A name that
          matches nothing declared here belongs to the framework or to a package, and is
          counted as an import rather than guessed at. A name that survives with more than
          one candidate is reported as unresolved and left out of the graph. The share that
          resolved is printed with the result, because it is the price of every number below.

        Evidence
          Each reference is graded, and the grade — not the metric — decides what may fail
          a run.

          proven    the reference stands where the language allows nothing but a type: a
                    construction, a base list, the type of a parameter, field, property or
                    return value, a generic argument list, an attribute, `typeof`, `sizeof`,
                    `default`, `catch`, or a type followed by the name it introduces.
          inferred  the name matches a declaration, but the position does not prove it: a
                    member access, an argument, a local, a cast.

        Formulas
          module dependency cycle       a set of namespaces that all reach each other
                                        through proven references between the types they
                                        declare. A namespace never depends on itself here.
          resolved outgoing type refs   how many distinct declared types one type names.
          resolved incoming type refs   how many distinct declared types name it.
          external import fan-out       imports of one file that name no namespace or type
                                        declared in this repository.

        Why a cycle is blocking
          A cycle is the one finding here that is proved rather than estimated: every edge
          of it stands in a position that can hold nothing but a type, and every name in it
          resolved to exactly one declaration. Its consequence is not a matter of taste —
          modules in a cycle cannot be read, moved, extracted or reused in one direction,
          and no ordering of them exists. Break one reference, move the shared concept into
          a module both may depend on, or accept it in writing with a `suppress` entry that
          says why. The counts are not blocking: they are approximate, and an approximate
          measurement does not get to impose one architectural taste on a repository.

        Limits
          Nothing bound by the compiler is here. Extension method targets, types inferred
          through `var`, overload resolution, implicit conversions, members inherited from
          framework base types and anything wired by a container or by reflection are
          invisible to a reader that has no symbol table. Coupling is therefore understated,
          never overstated, on the proven grade. Conditional compilation is not evaluated:
          every branch of the source is read. Partial types declared across several files
          are one subject and their references are merged. A local or a member whose name is
          exactly a declared type's name can create an inferred edge that does not exist.

        Possible damage
          Acting on an inferred edge can move code for a dependency that was never there.
          Open the reported line before believing it. A cycle names the exact references
          that close it; if one of them is wrong, the cycle is wrong, and the finding should
          be suppressed with that as the reason rather than repaired by a refactor.

        Comparison points
          The numbers the counts are reported against are comparison points, not thresholds
          and not budgets. They exist so a value has a scale, and they are configured under
          `settings.dependencies.csharp` in `.harness.json`.

        Remediation
          For a cycle, read every reference it lists and decide which direction the design
          actually wants; the usual repair is that a type known to both belongs in neither.
          For a high outgoing count, ask whether the type is orchestrating something that
          could be handed to it instead. For a high incoming count, remember that being
          depended upon is what a well-placed abstraction is for: it is a reason to keep it
          stable, not a defect. Engineering judgement decides here; the harness supplies the
          evidence and will not edit the code.
        """;
}
