using System.Text.Json;
using Harness.Repository;
using Harness.Versioning;

namespace Harness.Config;

internal static class FrameUpgrade
{
    public static (string? Report, string? Failure) Raise(IRepository repository, bool dryRun)
    {
        var path = Path.Combine(repository.RootPath, HarnessConfig.FileName);
        if (!repository.TrackedEntries.Any(entry => entry.Path == HarnessConfig.FileName))
        {
            return (null, $"'{HarnessConfig.FileName}' must be tracked before it can be upgraded.");
        }

        string text;
        try
        {
            text = File.ReadAllText(path);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return (null, $"Could not read '{path}': {exception.Message}");
        }

        var (pin, failure) = ReadPin(text);
        if (pin is null)
        {
            return (null, failure);
        }

        if (pin is "latest" || pin == HarnessVersion.Current.ToString())
        {
            return ($"{HarnessConfig.FileName} already runs contract {pin}; there is no pin to raise.\n", null);
        }

        if (!HarnessVersion.TryParse(pin, out var version))
        {
            return (null, $"'version' is not a harness release: {pin}.");
        }

        if (IsNewer(version, HarnessVersion.Current))
        {
            return (null, $"This binary is harness {HarnessVersion.Current} and cannot migrate the newer pin {pin}; update the harness first.");
        }

        if (!dryRun)
        {
            var rewriteFailure = Rewrite(path, text, pin, HarnessVersion.Current.ToString());
            if (rewriteFailure is not null)
            {
                return (null, rewriteFailure);
            }
        }

        var action = dryRun ? "Would raise" : "Raised";
        return ($$"""
        {{action}} {{HarnessConfig.FileName}} from {{pin}} to {{HarnessVersion.Current}}.
        Contract 2.0 migration:
          removed  maintainability.csharp, cohesion.csharp, suppress, overrides and legacy defaults
          added    architecture: { "standard": "sliced-dotnet/1" } or { "applicable": false, "reason": "..." }
          added    explicit applicability, settings and policy entries for every shipped check
          added    tracked .harness.budget.json with complexity.csharp propagationCost and coreSize
        Release 2.4 additions:
          added    architecture.sliced-dotnet advisory observations flat-directory-grouping,
                   mutual-cross-api, cross-api-fan-in and directories-by-purpose; they never
                   change the exit code, and no config change is needed
        Release 2.5 additions:
          added    architecture.sliced-dotnet layer = assembly invariants: every canonical
                   layer holding C# sources is exactly one .csproj, a Compile Include cannot
                   reach another layer, and ProjectReference edges between the zone's
                   projects follow the layer table; blocking for repositories that still
                   compile several layers into one project — split the projects, no config
                   change is needed
        Release 2.6 changes:
          changed  complexity.csharp measures the product: the files inside the architecture
                   zones of sliced-dotnet/1, so tests and tooling outside a zone no longer
                   enter the DSM; a repository without a zone is still measured whole
          changed  .harness.budget.json budgets meanReach (files a change reaches on average,
                   itself included) instead of propagationCost; the report still prints
                   propagation cost for comparison with the literature, and names tracked
                   files an <auto-generated> marker keeps out of the graph — run
                   `harness budget update` to migrate the budget, review it and commit it
        Release 2.7 additions:
          added    editorconfig.dotnet requires the tracked .editorconfig chain above every
                   SDK-style project to carry the shared code-style baseline (LF, final
                   newline, 4 spaces, IDE0055/0065/0161/0011/0040/0007 as warnings and the
                   options behind them, Allman braces); `harness explain editorconfig.dotnet`
                   prints the reference file, `harness init` writes it where none exists
          added    warning-suppressions.dotnet blocks #pragma warning disable, SuppressMessage,
                   NoWarn, WarningsNotAsErrors and editorconfig severities none/silent/
                   suggestion outside generated code, unless the code is allowed with a
                   reason in settings.warning-suppressions.dotnet.allowed
          added    policy entries for both checks and the settings section
                   "warning-suppressions.dotnet": { "allowed": {} } are required
        Review these sections, then run `harness check --verbose`. {{(dryRun ? "Nothing was written." : "Only the pin was changed; repository answers were not guessed.")}}
        """ + "\n", null);
    }

    private static (string? Pin, string? Failure) ReadPin(string text)
    {
        try
        {
            using var document = JsonDocument.Parse(text, new JsonDocumentOptions
            {
                CommentHandling = JsonCommentHandling.Skip,
                AllowTrailingCommas = true,
            });
            if (document.RootElement.ValueKind != JsonValueKind.Object
                || !document.RootElement.TryGetProperty("version", out var version)
                || version.ValueKind != JsonValueKind.String)
            {
                return (null, "'version' must be a string before the frame can be upgraded.");
            }

            return (version.GetString(), null);
        }
        catch (JsonException exception)
        {
            return (null, $"'{HarnessConfig.FileName}' is not readable as JSON ({exception.Message}).");
        }
    }

    private static bool IsNewer(HarnessVersion candidate, HarnessVersion current)
        => candidate.Major > current.Major
            || (candidate.Major == current.Major && candidate.Minor > current.Minor)
            || (candidate.Major == current.Major
                && candidate.Minor == current.Minor
                && candidate.Patch > current.Patch);

    private static string? Rewrite(string path, string text, string from, string target)
    {
        var current = $"\"{from}\"";
        var key = text.IndexOf("\"version\"", StringComparison.Ordinal);
        var value = key < 0 ? -1 : text.IndexOf(current, key, StringComparison.Ordinal);
        if (value < 0)
        {
            return $"Could not find the pinned value {current} in '{path}'.";
        }

        try
        {
            File.WriteAllText(path, string.Concat(
                text.AsSpan(0, value),
                $"\"{target}\"",
                text.AsSpan(value + current.Length)));
            return null;
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return $"Could not write '{path}': {exception.Message}";
        }
    }
}
