using Harness.Languages;

namespace Harness.Checks.Duplication;

/// <summary>Long-form content for `harness explain duplication.&lt;language&gt;`.</summary>
internal static class DuplicationExplanation
{
    public static string For(Language language)
        => language == Language.TypeScript ? TypeScript : Rationale + Discovery(language) + Normalization(language) + Unit + Names + Limits(language) + Tail(language);

    private const string TypeScript =
        """
        Rationale
          Repeated TS/JS source across files can indicate a copied rule. The shared
          tokenizer masks comments and literals, preserves keywords and operators, and
          replaces identifiers with one token. Tests and stories are included. Generated
          and build-output locations are excluded.

        Measurement
          A match needs 30 normalized lines and 90 tokens by default, declared in
          settings.duplication.typescript. A lexical match is a place to inspect, not
          proof that the two blocks have identical behavior.

        Remediation
          Read both blocks and extract a shared rule only when they must change together.

        Decision
          adrs/0064-typescript-language-axis.md
        """;

    private const string Rationale =
        """
        Rationale
          The same structure written out in several files is the cheapest observable sign
          that an abstraction is missing, or that one was copied instead of called. The
          gate finds where that happened and stops there. A lexical match is a reason to
          read two places, not proof that they mean the same thing. The initialized profile
          nevertheless makes the calibrated large-match window required; advisory remains
          an explicit migration state while a repository pays known findings down.


        """;

    private static string Discovery(Language language)
        => language == Language.Go
            ? """
              Discovery
                Every Git-tracked `.go` file the go tool would build is analyzed, test files
                included. Generated, vendored and build-output locations, `vendor/` and `testdata/`
                directories, directories starting with `_` or `.`, and files carrying the canonical
                `// Code generated ... DO NOT EDIT.` header or a `//go:build ignore` constraint
                before the package clause are excluded. Exclusion is by name and by declared
                marker only, so a reader can predict it, and no build tag but `ignore` standing
                alone is evaluated. A repository with no remaining Go source is not
                applicable, never a pass.


              """
            : """
              Discovery
                Every Git-tracked `.cs` file is analyzed. Generated, vendored and build-output
                locations are excluded, as are files named `*.g.cs`, `*.generated.cs` and
                `*.Designer.cs`, and files whose first five lines carry the `<auto-generated>`
                marker. Exclusion is by name and by declared marker only, so a reader can predict
                it, and no repository-local analyzer script or exclusion list is involved. A
                repository with no remaining C# source is not applicable, never a pass.


              """;

    private static string Normalization(Language language)
    {
        var reserved = language == Language.Go
            ? """
                comment, directive        contributes nothing
                string literal            one `"` token, whatever it contains; a raw string
                                          spanning lines is one token on the line it opens
                rune literal              one `'` token, whatever it contains
                numeric literal           one `#` token
                Go keyword, predeclared   itself, so `if` and `for` never match each other and
                identifier or builtin     `len`, `error` and `nil` keep their shape
              """
            : """
                comment, directive        contributes nothing
                string literal            one `"` token, whatever it contains
                character literal         one `'` token, whatever it contains
                numeric literal           one `#` token
                C# keyword                itself, so `if` and `while` never match each other
              """;
        var reduced = language == Language.Go
            ? "comment text and string, raw string and rune content are replaced with spaces"
            : "comment text, string and character literal content, and preprocessor directives\n    are replaced with spaces";
        return $"""
            Normalization
              Each file is first reduced to code: {reduced}. What remains is
              turned into one token sequence per physical line, by these rules and no others:

            {reserved}
                any other word            `n`, so every identifier reads the same
                any other character       itself
                whitespace                separates tokens and never survives; a line with no
                                          tokens leaves no trace, so blank lines and reflowed
                                          formatting do not affect a match


            """;
    }

    private const string Unit =
        """
        Unit of comparison
          The unit is a configurable window of consecutive normalized lines carrying a
          configurable minimum number of tokens in total. The initialized profile uses 30 lines and 90
          tokens. Two windows repeat when their token sequences are identical. Windows
          below the token count are not compared at all: lines of braces, `return`s and
          closing parentheses are identical in every file and are not something anyone can
          extract.

          A repetition is reported once, not once per window. When a group of matching
          windows is found it is grown line by line, backwards and forwards, for as long
          as every occurrence still agrees. What the report names is the whole repeated
          region, as a physical line span, in every file it occurs in.

          Growth stops at lines a repetition has already claimed, so no line is ever
          reported twice. Three copies of which two run longer than the third therefore
          read as two findings that do not overlap — what all three share, and then what
          the remaining two share — rather than as one finding quietly containing another.

          Only repetitions that span at least two files are reported. Repetition inside one
          file is left to the reader who already has the whole file open.


        """;

    private const string Names =
        """
        Names
          The name is the whole claim. `lexically repeated block` means the two regions
          produce the same tokens after the normalization above. That is
          not proven duplicate behaviour: the gate has no types, no bindings, no overload
          resolution and no notion of what any of the identifiers it erased referred to.


        """;

    private static string Limits(Language language)
        => language == Language.Go
            ? """
              Limits
                The reader is lexical. A raw string is one token however many lines it spans, so
                code kept inside one — templates, embedded SQL, fixtures — is not compared.
                Structurally identical code that differs by one token — an added argument, a
                different operator, `:=` against `=` — does not match, and a repetition shorter
                than the configured window is not reported at all. Build constraints are not
                evaluated: every file of the directory is read whatever `//go:build` says, so two
                platform-specific files that repeat each other are reported like any other pair.


              """
            : """
              Limits
                The reader is lexical. An interpolation hole is masked with the literal that
                contains it, so code written inside one is not compared. Structurally identical
                code that differs by one token — an added argument, a different operator — does
                not match, and a repetition shorter than the configured window is not reported at
                all. Conditional compilation is not evaluated: directives are removed and every
                branch of the source is read.


              """;

    private static string Tail(Language language)
    {
        var shapes = language == Language.Go
            ? """
                Normalization erases exactly what makes some similar-looking code different.
                Struct definitions, `if err != nil` ladders, table-driven test cases, option
                setters, handler wiring and generated-looking boilerplate all converge on the
                same tokens while referring to unrelated things; a run of them will be reported
                and is often nothing. Two implementations of the same interface that
                legitimately share a shape are reported for the same reason.
              """
            : """
                Normalization erases exactly what makes some similar-looking code different.
                Property and field declarations, `switch` arms, builder chains, DTO shapes, test
                arrange blocks and generated-looking boilerplate all converge on the same tokens
                while referring to unrelated things; a run of them will be reported and is often
                nothing. Two implementations of the same interface that legitimately share a
                shape are reported for the same reason.
              """;
        return $"""
            False positives
            {shapes}
            Possible damage
              Extracting a shared helper from two blocks that only look alike couples two
              things that had no reason to change together, and every later change to one of
              them then arrives as a parameter or a flag on the shared helper. That is worse
              than the repetition it removed. A match that does not survive reading should be
              handled by tuning the detector or by advisory policy instead of forcing the wrong
              abstraction.

            Remediation
              Open both locations before deciding anything. Extract when the two blocks encode
              one rule that must stay the same — when a change to one would be a bug if it did
              not reach the other. Leave them alone when they merely look alike, when they
              belong to different layers or bounded contexts, when they are tests whose
              explicitness is the point, or when the shared abstraction would need a parameter
              for every difference. Engineering judgement decides here; the harness supplies
              the evidence and will not edit the code. Keep the initialized `30/90` profile in
              `settings.{language.Qualify("duplication")}` unless repository evidence justifies a
              different detector; use advisory policy temporarily while known matches are paid
              down, or `off` only when the whole measurement is unwanted.
            """;
    }
}
