using Harness.Languages;
using Harness.Structure;

namespace Harness.Checks.Complexity;

/// <summary>
/// Which nodes the DSM measures: the product, read from the tree and never from an answer.
/// C# files inside the architecture zones, else outside the test projects, else the whole
/// repository; a Go module graph whole, with the `main` packages as its composition root.
/// </summary>
internal sealed record DsmScope(
    SourceGraph Graph,
    Language Language,
    string Unit,
    IReadOnlyList<string> Zones,
    IReadOnlyList<string> TestProjects,
    IReadOnlyList<string> CompositionRoots,
    int OutsideFiles)
{
    public static DsmScope Of(
        SourceGraph graph,
        bool architectureApplicable,
        IReadOnlyList<string> trackedPaths,
        IReadOnlyList<(string Path, bool IsTest)> projects)
    {
        var zones = architectureApplicable ? ArchitectureZones.Discover(trackedPaths) : [];
        if (zones.Count > 0)
        {
            var inside = graph.Within(path => ArchitectureZones.Contains(zones, path));
            return new DsmScope(inside, Language.CSharp, "file", zones, [], [], graph.SourcePaths.Count - inside.SourcePaths.Count);
        }

        var testDirectories = projects
            .Where(project => project.IsTest)
            .Select(project => DirectoryOf(project.Path))
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToList();
        if (testDirectories.Count == 0)
        {
            return new DsmScope(graph, Language.CSharp, "file", [], [], [], 0);
        }

        var owners = projects.Select(project => DirectoryOf(project.Path)).ToHashSet(StringComparer.Ordinal);
        var tests = testDirectories.ToHashSet(StringComparer.Ordinal);
        var product = graph.Within(path => NearestProject(path, owners) is not { } owner || !tests.Contains(owner));
        return new DsmScope(product, Language.CSharp, "file", [], testDirectories, [], graph.SourcePaths.Count - product.SourcePaths.Count);
    }

    public static DsmScope OfPackages(SourceGraph graph)
        => new(
            graph,
            Language.Go,
            "package",
            [],
            [],
            graph.Types.Where(package => package.Name == "main").Select(package => package.Path).Order(StringComparer.Ordinal).ToList(),
            0);

    public static DsmScope OfTypeScript(SourceGraph graph)
        => new(graph, Language.TypeScript, "file", [], [], [], 0);

    public string Location
        => Zones.Count == 0 ? "." : string.Join(", ", Zones.Select(ArchitectureZones.Display));

    public bool IsCompositionRoot(string path)
        => Zones.Any(zone => ArchitectureZones.Relative(path, zone).StartsWith("Host/", StringComparison.Ordinal))
            || CompositionRoots.Contains(path, StringComparer.Ordinal);

    public string Describe()
    {
        var measured = Graph.SourcePaths.Count;
        if (Language == Language.Go)
        {
            var roots = CompositionRoots.Count switch
            {
                0 => "no main package",
                1 => $"1 main package [{CompositionRoots[0]}] is the composition root",
                _ => $"{CompositionRoots.Count} main packages [{string.Join(", ", CompositionRoots)}] are the composition root",
            };
            return $"scope: {measured} authored packages of the tracked go.mod modules (test files are not read; {roots})";
        }

        if (Language == Language.TypeScript)
        {
            return $"scope: {measured} authored TypeScript/JavaScript files (tests and transparent barrels excluded)";
        }

        if (Zones.Count > 0)
        {
            var zoneList = string.Join(", ", Zones.Select(ArchitectureZones.Display));
            return $"scope: {measured} files inside architecture zone{(Zones.Count == 1 ? "" : "s")} [{zoneList}]; "
                + Outside("outside the zones");
        }

        if (TestProjects.Count > 0)
        {
            var projectList = string.Join(", ", TestProjects.Select(ArchitectureZones.Display));
            return $"scope: {measured} authored files outside {TestProjects.Count} test "
                + $"project{(TestProjects.Count == 1 ? "" : "s")} [{projectList}] (no architecture zone); "
                + Outside("under test projects");
        }

        return $"scope: {measured} authored files (no architecture zone; the repository is measured whole)";
    }

    public string? DescribeMarkedGenerated()
    {
        var count = Graph.MarkedGenerated.Count;
        if (count == 0)
        {
            return null;
        }

        var header = Language == Language.Go ? "a `Code generated ... DO NOT EDIT.` header" : "an <auto-generated> header";
        var files = count == 1
            ? $"1 tracked {Language.Name} file with {header} is not read"
            : $"{count} tracked {Language.Name} files with {header} are not read";
        return $"generated markers: {files}: "
            + string.Join(", ", Graph.MarkedGenerated.Take(5))
            + (count > 5 ? $", and {count - 5} more" : "");
    }

    /// <summary>Go files under `//go:build ignore`: the go tool never builds them, so they lend no edge.</summary>
    public string? DescribeMarkedIgnored()
    {
        var count = Graph.MarkedIgnored.Count;
        if (count == 0)
        {
            return null;
        }

        var files = count == 1
            ? $"1 tracked {Language.Name} file under a `//go:build ignore` constraint is not read"
            : $"{count} tracked {Language.Name} files under a `//go:build ignore` constraint are not read";
        return $"build constraints: {files}: "
            + string.Join(", ", Graph.MarkedIgnored.Take(5))
            + (count > 5 ? $", and {count - 5} more" : "");
    }

    private string Outside(string where)
        => OutsideFiles == 1
            ? $"1 authored file {where} is not measured"
            : $"{OutsideFiles} authored files {where} are not measured";

    /// <summary>The directory of the closest project at or above the file, or null when no project owns it.</summary>
    private static string? NearestProject(string path, HashSet<string> projectDirectories)
    {
        var directory = DirectoryOf(path);
        while (true)
        {
            if (projectDirectories.Contains(directory))
            {
                return directory;
            }

            if (directory.Length == 0)
            {
                return null;
            }

            directory = DirectoryOf(directory);
        }
    }

    private static string DirectoryOf(string path)
    {
        var separator = path.LastIndexOf('/');
        return separator < 0 ? string.Empty : path[..separator];
    }
}
