namespace Harness.Repository;

/// <summary>One authorship decision for every tracked source, independent of its check.</summary>
internal static class EvidenceClassifier
{
    private static readonly string[] CSharpSuffixes = [".g.cs", ".generated.cs", ".designer.cs"];
    private static readonly string[] TypeScriptSuffixes = [".generated.ts", ".g.ts", ".min.js", ".min.mjs"];

    public static EvidenceKind Classify(
        TrackedEntry entry,
        IReadOnlyList<string> declaredGeneratedPaths,
        Func<TrackedEntry, (string? Text, string? Failure)> readTrackedText)
    {
        var path = entry.Path;
        if (entry.IsSymbolicLink)
        {
            return EvidenceKind.Authored;
        }

        if (path.EndsWith(".d.ts", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".d.mts", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".d.cts", StringComparison.OrdinalIgnoreCase))
        {
            return EvidenceKind.ToolchainIgnored;
        }

        if (path.EndsWith(".go", StringComparison.Ordinal))
        {
            var directories = path.Split('/').SkipLast(1);
            if (directories.Any(segment => segment is "vendor" or "testdata" || segment.StartsWith('_') || segment.StartsWith('.')))
            {
                return EvidenceKind.ToolchainIgnored;
            }

            var (source, _) = readTrackedText(entry);
            if (source is not null && source.Split('\n')
                .TakeWhile(line => !line.StartsWith("package ", StringComparison.Ordinal))
                .Any(line => line.Trim() is "//go:build ignore" or "// +build ignore"))
            {
                return EvidenceKind.ToolchainIgnored;
            }
        }

        if (path.EndsWith(".yml", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".yaml", StringComparison.OrdinalIgnoreCase))
        {
            if (path.Split('/').SkipLast(1).Contains("molecule", StringComparer.Ordinal))
            {
                return EvidenceKind.ToolchainIgnored;
            }
        }

        var marker = Marker(entry, readTrackedText);
        if (marker is null)
        {
            return EvidenceKind.Authored;
        }

        return declaredGeneratedPaths.Any(declared => path == declared || path.StartsWith(declared + "/", StringComparison.Ordinal))
            ? EvidenceKind.DeclaredGenerated
            : EvidenceKind.UndeclaredMarker;
    }

    private static string? Marker(TrackedEntry entry, Func<TrackedEntry, (string? Text, string? Failure)> readTrackedText)
    {
        var path = entry.Path;
        if (CSharpSuffixes.Any(suffix => path.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
            || TypeScriptSuffixes.Any(suffix => path.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)))
        {
            return "generated filename suffix";
        }

        if (!path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)
            && !path.EndsWith(".go", StringComparison.Ordinal)
            && !path.EndsWith(".ts", StringComparison.OrdinalIgnoreCase)
            && !path.EndsWith(".tsx", StringComparison.OrdinalIgnoreCase)
            && !path.EndsWith(".js", StringComparison.OrdinalIgnoreCase)
            && !path.EndsWith(".jsx", StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        var (text, _) = readTrackedText(entry);
        if (text is null)
        {
            return null;
        }

        var head = text.Split('\n').Take(5).ToList();
        if (head.Any(line => line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
            || line.Contains("<autogenerated", StringComparison.OrdinalIgnoreCase)
            || line.Contains("@generated", StringComparison.OrdinalIgnoreCase)))
        {
            return "generated header";
        }

        if (path.EndsWith(".go", StringComparison.Ordinal))
        {
            if (text.Split('\n').TakeWhile(line => !line.StartsWith("package ", StringComparison.Ordinal))
                .Any(line => line.StartsWith("// Code generated ", StringComparison.Ordinal)
                    && line.TrimEnd('\r').EndsWith(" DO NOT EDIT.", StringComparison.Ordinal)))
            {
                return "Go generated header";
            }

        }

        return null;
    }
}
