using System.Text.Json;
using Harness.Repository;
using Harness.Versioning;

namespace Harness.Config;

internal static class FrameUpgrade
{
    public static (string? Report, string? Failure) Raise(IRepository repository, bool dryRun)
    {
        var path = Path.Combine(repository.RootPath, HarnessConfig.FileName);
        if (!repository.TrackedEntries.Any(entry => entry.Path == HarnessConfig.FileName))
        {
            return (null, $"'{HarnessConfig.FileName}' must be tracked before it can be upgraded.");
        }

        string text;
        try
        {
            text = File.ReadAllText(path);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return (null, $"Could not read '{path}': {exception.Message}");
        }

        var (pin, failure) = ReadPin(text);
        if (pin is null)
        {
            return (null, failure);
        }

        if (pin is "latest" || pin == HarnessVersion.Current.ToString())
        {
            return ($"{HarnessConfig.FileName} already runs contract {pin}; there is no pin to raise.\n", null);
        }

        if (!HarnessVersion.TryParse(pin, out var version))
        {
            return (null, $"'version' is not a harness release: {pin}.");
        }

        if (IsNewer(version, HarnessVersion.Current))
        {
            return (null, $"This binary is harness {HarnessVersion.Current} and cannot migrate the newer pin {pin}; update the harness first.");
        }

        if (!dryRun)
        {
            var rewriteFailure = Rewrite(path, text, pin, HarnessVersion.Current.ToString());
            if (rewriteFailure is not null)
            {
                return (null, rewriteFailure);
            }
        }

        var action = dryRun ? "Would raise" : "Raised";
        return ($$"""
        {{action}} {{HarnessConfig.FileName}} from {{pin}} to {{HarnessVersion.Current}}.
        Contract 2.0 migration:
          removed  maintainability.csharp, cohesion.csharp, suppress, overrides and legacy defaults
          added    architecture: { "standard": "sliced-dotnet/1" } or { "applicable": false, "reason": "..." }
          added    explicit applicability, settings and policy entries for every shipped check
          added    tracked .harness.budget.json with complexity.csharp propagationCost and coreSize
                   (retired again in 2.15, see below)
        Release 2.4 additions:
          added    architecture.sliced-dotnet advisory observations flat-directory-grouping,
                   mutual-cross-api, cross-api-fan-in and directories-by-purpose; they never
                   change the exit code, and no config change is needed
        Release 2.5 additions:
          added    architecture.sliced-dotnet layer = assembly invariants: every canonical
                   layer holding C# sources is exactly one .csproj, a Compile Include cannot
                   reach another layer, and ProjectReference edges between the zone's
                   projects follow the layer table; blocking for repositories that still
                   compile several layers into one project — split the projects, no config
                   change is needed
        Release 2.6 changes:
          changed  complexity.csharp measures the product: the files inside the architecture
                   zones of sliced-dotnet/1, so tests and tooling outside a zone no longer
                   enter the DSM; a repository without a zone is still measured whole
          changed  complexity.csharp measures meanReach (files a change reaches on average,
                   itself included) instead of propagationCost; the report still prints
                   propagation cost for comparison with the literature, and names tracked
                   files an <auto-generated> marker keeps out of the graph
        Release 2.7 additions:
          added    comments.yaml and comments.typescript: the comment density rule now reads
                   tracked YAML and TypeScript/JavaScript through their own lexical readers;
                   declare applicability yaml and typescript, settings comments.yaml and
                   comments.typescript (minimumCommentLines, percentageLimit) and a policy
                   entry for each check
        Release 2.8 additions:
          added    editorconfig.dotnet requires the tracked .editorconfig chain above every
                   SDK-style project to carry the shared code-style baseline (LF, final
                   newline, 4 spaces, IDE0055/0065/0161/0011/0040/0007 as warnings and the
                   options behind them, Allman braces); `harness explain editorconfig.dotnet`
                   prints the reference file, `harness init` writes it where none exists
          added    warning-suppressions.dotnet blocks address-level silencing: #pragma
                   warning disable, SuppressMessage, NoWarn in a project file and
                   editorconfig severities none/silent/suggestion in a path-scoped
                   section, outside generated code; a rule switched off for the whole
                   repository ([*.cs] in .editorconfig or NoWarn in Directory.Build.props)
                   stays allowed and is printed as an observation on every run
          added    policy entries for both checks are required; no settings section
        Release 2.9 changes:
          changed  harness init writes duplication.csharp as required with the existing
                   calibrated 30-line / 90-token profile; existing explicit advisory or off
                   policy remains valid and upgrade changes only the version pin
          added    answers.verify names the tracked repository-owned script that runs every
                   applicable quality check, including `harness check`; frame.verify is
                   required by default, while the harness records the path but never runs
                   or inspects the repository toolchain
        Release 2.10 changes:
          changed  complexity.csharp draws the product boundary without an architecture zone
                   from tracked project files: authored .cs files whose nearest .csproj is a
                   test project (Microsoft.NET.Test.Sdk, xunit, NUnit, MSTest, TUnit,
                   IsTestProject or MSTest.Sdk) leave the DSM, so a monolith or a library is
                   no longer measured together with its test hosts; sliced-dotnet zones are
                   unchanged, and a repository without any test project is still measured
                   whole
        Release 2.11 changes:
          changed  answers.tests.unit and answers.tests.integration address a test project —
                   its directory or project file — never the test files inside it: a paths
                   entry ending in .cs, .ts, .tsx, .js or another source suffix the harness
                   reads makes the question Incomplete and the report names the directories
                   to list instead; every paths answer holds at most 5 addresses
        Release 2.12 changes:
          changed  sliced-dotnet/1 no longer names a Shared layer: Domain is the bottom of the
                   layer DAG and references no other layer, and Domain/Shared stays the reserved
                   home of concepts that belong to no slice; a Shared directory directly below a
                   zone is now outside every canonical layer, so move its code into Domain (a
                   slice or Domain/Shared) and fold the Shared project into the Domain project
        Release 2.13 changes:
          changed  sliced-dotnet/1 puts slices directly in the layer root: Application/<Slice>,
                   Api/<Slice>, Consumers/<Slice>, Infrastructure/<Slice> and Domain/<Slice>, with
                   one optional group level as before; the Features/ directory is gone — move
                   <Layer>/Features/<Slice> to <Layer>/<Slice>; only Domain/Shared and
                   Infrastructure/Persistence stay reserved, every other directory in the root of
                   a sliced layer must be a slice (no-segments-on-sliced-layers,
                   orphan-slice-mirror) — move cross-cutting web plumbing into Host or a slice
          added    no-layer-public-api blocks a Contracts/ directory directly below a sliced
                   layer: a slice publishes its own Contracts/, the layer has none
          added    advisory observations repetitive-naming (every slice sits in one group) and
                   ambiguous-slice-names (a direct segment repeats its slice name); they never
                   change the exit code
          kept     the standard is still named sliced-dotnet/1: the shape is named by the
                   contract pin, not by a version inside the standard name
        Release 2.14 changes:
          changed  the managed commit-msg hook holds no binary path: it resolves the harness when
                   it runs — the clone-local <git-common-dir>/harness/bin/harness that
                   `install.sh --scope clone` writes, then `harness` on PATH — and refuses the
                   commit, naming both places, when it finds neither; the hook is now the same
                   text in every clone, so commits.setup no longer depends on which binary wrote
                   it or which one runs the check, and `harness setup` rewrites a hook an older
                   release pinned to a fixed path
          added    commits.setup names what differs — the missing managed file, an unmanaged file
                   in its place, the dead path an older hook exec's, the places searched for a
                   binary — and blocks when the resolved harness is not the pinned release; run
                   `harness setup` after installing the pinned release, no config change is needed
        Release 2.15 changes:
          removed  .harness.budget.json and `harness budget update`: complexity.csharp no longer
                   compares the DSM with a tracked ratchet; a tracked budget file makes the
                   frame Incomplete until you `git rm .harness.budget.json` and commit
          added    settings.complexity.csharp with meanReach (files, at least 1) and coreSize
                   (files) — the ceiling the check compares the DSM with; the contract defaults
                   are 8.0 and 0, the values of sliced-dotnet/1 that `harness init` writes, and
                   like every settings section it is required and reviewed with the frame
          changed  exceeding either value is blocking under required, and the report names the
                   files outside Host whose own reach is largest — cut edges there, or set the
                   check to advisory or off in policy knowingly; there is no update command
        Review these sections, then run `harness check --verbose`. {{(dryRun ? "Nothing was written." : "Only the pin was changed; repository answers were not guessed.")}}
        """ + "\n", null);
    }

    private static (string? Pin, string? Failure) ReadPin(string text)
    {
        try
        {
            using var document = JsonDocument.Parse(text, new JsonDocumentOptions
            {
                CommentHandling = JsonCommentHandling.Skip,
                AllowTrailingCommas = true,
            });
            if (document.RootElement.ValueKind != JsonValueKind.Object
                || !document.RootElement.TryGetProperty("version", out var version)
                || version.ValueKind != JsonValueKind.String)
            {
                return (null, "'version' must be a string before the frame can be upgraded.");
            }

            return (version.GetString(), null);
        }
        catch (JsonException exception)
        {
            return (null, $"'{HarnessConfig.FileName}' is not readable as JSON ({exception.Message}).");
        }
    }

    private static bool IsNewer(HarnessVersion candidate, HarnessVersion current)
        => candidate.Major > current.Major
            || (candidate.Major == current.Major && candidate.Minor > current.Minor)
            || (candidate.Major == current.Major
                && candidate.Minor == current.Minor
                && candidate.Patch > current.Patch);

    private static string? Rewrite(string path, string text, string from, string target)
    {
        var current = $"\"{from}\"";
        var key = text.IndexOf("\"version\"", StringComparison.Ordinal);
        var value = key < 0 ? -1 : text.IndexOf(current, key, StringComparison.Ordinal);
        if (value < 0)
        {
            return $"Could not find the pinned value {current} in '{path}'.";
        }

        try
        {
            File.WriteAllText(path, string.Concat(
                text.AsSpan(0, value),
                $"\"{target}\"",
                text.AsSpan(value + current.Length)));
            return null;
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return $"Could not write '{path}': {exception.Message}";
        }
    }
}
