namespace Harness.Checks.DotNet;

internal static class WarningSuppressionsExplanation
{
    public const string Text =
        """
        Rationale
          build-properties.dotnet requires warnings to be errors; that baseline holds only while
          nobody silences the warnings one by one. Suppressions accumulate quietly and each looks
          reasonable in its own diff, so the repository decides once, in the tracked frame, which
          diagnostics it accepts silencing and why.

        What it reads
          Tracked authored .cs files (generated suffixes, generated directories and files with an
          <auto-generated> marker are skipped), every tracked SDK-style project and
          Directory.Build.props, and every tracked .editorconfig. The toolchain is not executed.

        What fails
          `#pragma warning disable` with any code, or with none; `[SuppressMessage]` and
          `[UnconditionalSuppressMessage]`; `NoWarn` and `WarningsNotAsErrors` entries;
          `dotnet_diagnostic.<code>.severity` set to none, silent or suggestion in a section that
          is not `generated_code = true`; and any `dotnet_analyzer_diagnostic` severity that
          silences a whole category — unless the code is allowed in settings:

          "settings": {
            "warning-suppressions.dotnet": {
              "allowed": { "CS1591": "public API is not documented; IDE0005 needs the XML file" }
            }
          }

          An allowed code is a repository-wide comparison point with a reviewed reason; it is not
          the address-level suppression of a file or a finding that ADR-0035 refuses. Allowed
          codes in use are listed in the report so the list stays honest.

        Remediation
          Fix the code the diagnostic points at. When the diagnostic is wrong for this repository
          as a whole, add its code to `allowed` with the reason, in the same change. If the
          repository rejects the rule entirely, record that through
          `policy.warning-suppressions.dotnet`.

        Applicability
          Disable all .NET repository checks together only when they do not apply:

          "applicability": {
            "dotnet": { "applicable": false, "reason": "why .NET checks do not apply" }
          }
        """;
}
